// Auto-generated by scripts/build-country-augment.mjs — do not edit by hand.
// Sources: World Bank (most recent value per indicator) + derived from
// country-data.ts (population density).

export interface CountryAugmented {
  /** Derived from population / area — "344 /km²". */
  populationDensity?: string;
  /** CO₂ emissions per capita (tonnes CO₂e/year, excl. LULUCF). */
  co2PerCapita?: string;
  /** Urban population share (%). */
  urbanPct?: string;
  /** Fertility rate (births per woman). */
  fertilityRate?: string;
  /** International migrant stock (%). */
  migrantPct?: string;
}

export const COUNTRY_AUGMENTED: Record<string, CountryAugmented> = {
  "Afghanistan": {
    "populationDensity": "67.5 /km²",
    "co2PerCapita": "0.28 t",
    "urbanPct": "26%",
    "fertilityRate": "4.8",
    "migrantPct": "0.2%"
  },
  "Albania": {
    "populationDensity": "69.0 /km²",
    "co2PerCapita": "1.8 t",
    "urbanPct": "59%",
    "fertilityRate": "1.3",
    "migrantPct": "1.7%"
  },
  "Algeria": {
    "populationDensity": "19.6 /km²",
    "co2PerCapita": "4.0 t",
    "urbanPct": "75%",
    "fertilityRate": "2.7",
    "migrantPct": "0.6%"
  },
  "Angola": {
    "populationDensity": "30.0 /km²",
    "co2PerCapita": "0.74 t",
    "urbanPct": "71%",
    "fertilityRate": "5.0",
    "migrantPct": "1.8%"
  },
  "Antarctica": {
    "populationDensity": "0.0 /km²"
  },
  "Argentina": {
    "populationDensity": "16.8 /km²",
    "co2PerCapita": "4.0 t",
    "urbanPct": "92%",
    "fertilityRate": "1.5",
    "migrantPct": "4.3%"
  },
  "Armenia": {
    "populationDensity": "100 /km²",
    "co2PerCapita": "2.5 t",
    "urbanPct": "66%",
    "fertilityRate": "1.7",
    "migrantPct": "9.2%"
  },
  "Australia": {
    "populationDensity": "3.6 /km²",
    "co2PerCapita": "14.1 t",
    "urbanPct": "88%",
    "fertilityRate": "1.5",
    "migrantPct": "30%"
  },
  "Austria": {
    "populationDensity": "107 /km²",
    "co2PerCapita": "6.3 t",
    "urbanPct": "69%",
    "fertilityRate": "1.3",
    "migrantPct": "26%"
  },
  "Azerbaijan": {
    "populationDensity": "115 /km²",
    "co2PerCapita": "3.8 t",
    "urbanPct": "59%",
    "fertilityRate": "1.4",
    "migrantPct": "2.1%"
  },
  "Bahamas": {
    "populationDensity": "28.4 /km²",
    "co2PerCapita": "3.6 t",
    "urbanPct": "81%",
    "fertilityRate": "1.4",
    "migrantPct": "17%"
  },
  "Bangladesh": {
    "populationDensity": "1,149 /km²",
    "co2PerCapita": "0.72 t",
    "urbanPct": "33%",
    "fertilityRate": "2.1",
    "migrantPct": "1.7%"
  },
  "Belarus": {
    "populationDensity": "43.3 /km²",
    "co2PerCapita": "5.9 t",
    "urbanPct": "79%",
    "fertilityRate": "1.2",
    "migrantPct": "12%"
  },
  "Belgium": {
    "populationDensity": "387 /km²",
    "co2PerCapita": "7.3 t",
    "urbanPct": "88%",
    "fertilityRate": "1.4",
    "migrantPct": "20%"
  },
  "Belize": {
    "populationDensity": "18.2 /km²",
    "co2PerCapita": "0.93 t",
    "urbanPct": "42%",
    "fertilityRate": "2.0",
    "migrantPct": "17%"
  },
  "Benin": {
    "populationDensity": "115 /km²",
    "co2PerCapita": "0.49 t",
    "urbanPct": "53%",
    "fertilityRate": "4.5",
    "migrantPct": "2.9%"
  },
  "Bhutan": {
    "populationDensity": "20.6 /km²",
    "co2PerCapita": "2.0 t",
    "urbanPct": "43%",
    "fertilityRate": "1.4",
    "migrantPct": "7.0%"
  },
  "Bolivia": {
    "populationDensity": "10.0 /km²",
    "co2PerCapita": "2.3 t",
    "urbanPct": "71%",
    "fertilityRate": "2.5",
    "migrantPct": "1.5%"
  },
  "Botswana": {
    "populationDensity": "3.4 /km²",
    "co2PerCapita": "2.7 t",
    "urbanPct": "67%",
    "fertilityRate": "2.7",
    "migrantPct": "4.6%"
  },
  "Brazil": {
    "populationDensity": "25.1 /km²",
    "co2PerCapita": "2.3 t",
    "urbanPct": "88%",
    "fertilityRate": "1.6",
    "migrantPct": "0.7%"
  },
  "Brunei": {
    "populationDensity": "76.0 /km²",
    "co2PerCapita": "20.2 t",
    "urbanPct": "75%",
    "fertilityRate": "1.7",
    "migrantPct": "26%"
  },
  "Bulgaria": {
    "populationDensity": "54.1 /km²",
    "co2PerCapita": "5.3 t",
    "urbanPct": "74%",
    "fertilityRate": "1.7",
    "migrantPct": "4.4%"
  },
  "Burundi": {
    "populationDensity": "429 /km²",
    "co2PerCapita": "0.07 t",
    "urbanPct": "25%",
    "fertilityRate": "4.8",
    "migrantPct": "2.8%"
  },
  "Cambodia": {
    "populationDensity": "99.4 /km²",
    "co2PerCapita": "1.1 t",
    "urbanPct": "41%",
    "fertilityRate": "2.5",
    "migrantPct": "0.5%"
  },
  "Cameroon": {
    "populationDensity": "61.1 /km²",
    "co2PerCapita": "0.35 t",
    "urbanPct": "55%",
    "fertilityRate": "4.3",
    "migrantPct": "2.2%"
  },
  "Canada": {
    "populationDensity": "4.2 /km²",
    "co2PerCapita": "14.0 t",
    "urbanPct": "83%",
    "fertilityRate": "1.3",
    "migrantPct": "22%"
  },
  "Chad": {
    "populationDensity": "14.6 /km²",
    "co2PerCapita": "0.14 t",
    "urbanPct": "27%",
    "fertilityRate": "6.0",
    "migrantPct": "6.3%"
  },
  "Chile": {
    "populationDensity": "26.5 /km²",
    "co2PerCapita": "3.9 t",
    "urbanPct": "89%",
    "fertilityRate": "1.1",
    "migrantPct": "7.8%"
  },
  "China": {
    "populationDensity": "144 /km²",
    "co2PerCapita": "9.3 t",
    "urbanPct": "66%",
    "fertilityRate": "1.0",
    "migrantPct": "0.1%"
  },
  "Colombia": {
    "populationDensity": "48.2 /km²",
    "co2PerCapita": "1.8 t",
    "urbanPct": "79%",
    "fertilityRate": "1.6",
    "migrantPct": "5.8%"
  },
  "Congo": {
    "populationDensity": "17.5 /km²",
    "co2PerCapita": "1.3 t",
    "urbanPct": "64%",
    "fertilityRate": "4.1",
    "migrantPct": "6.1%"
  },
  "Croatia": {
    "populationDensity": "70.2 /km²",
    "co2PerCapita": "4.8 t",
    "urbanPct": "58%",
    "fertilityRate": "1.5",
    "migrantPct": "14%"
  },
  "Cuba": {
    "populationDensity": "90.9 /km²",
    "co2PerCapita": "1.9 t",
    "urbanPct": "77%",
    "fertilityRate": "1.4",
    "migrantPct": "0.0%"
  },
  "Cyprus": {
    "populationDensity": "111 /km²",
    "co2PerCapita": "5.4 t",
    "urbanPct": "67%",
    "fertilityRate": "1.4",
    "migrantPct": "15%"
  },
  "Czechia": {
    "populationDensity": "139 /km²",
    "co2PerCapita": "7.1 t",
    "urbanPct": "73%",
    "fertilityRate": "1.4",
    "migrantPct": "9.5%"
  },
  "Denmark": {
    "populationDensity": "140 /km²",
    "co2PerCapita": "4.3 t",
    "urbanPct": "89%",
    "fertilityRate": "1.5",
    "migrantPct": "14%"
  },
  "Djibouti": {
    "populationDensity": "43.5 /km²",
    "co2PerCapita": "0.77 t",
    "urbanPct": "73%",
    "fertilityRate": "2.6",
    "migrantPct": "11%"
  },
  "Ecuador": {
    "populationDensity": "65.0 /km²",
    "co2PerCapita": "2.6 t",
    "urbanPct": "63%",
    "fertilityRate": "1.8",
    "migrantPct": "4.1%"
  },
  "Egypt": {
    "populationDensity": "107 /km²",
    "co2PerCapita": "2.5 t",
    "urbanPct": "43%",
    "fertilityRate": "2.7",
    "migrantPct": "1.0%"
  },
  "Eritrea": {
    "populationDensity": "33.9 /km²",
    "co2PerCapita": "0.22 t",
    "urbanPct": "35%",
    "fertilityRate": "3.7",
    "migrantPct": "0.4%"
  },
  "Estonia": {
    "populationDensity": "22.2 /km²",
    "co2PerCapita": "7.8 t",
    "urbanPct": "71%",
    "fertilityRate": "1.2",
    "migrantPct": "15%"
  },
  "Ethiopia": {
    "populationDensity": "102 /km²",
    "co2PerCapita": "0.15 t",
    "urbanPct": "24%",
    "fertilityRate": "3.9",
    "migrantPct": "0.9%"
  },
  "Fiji": {
    "populationDensity": "50.1 /km²",
    "co2PerCapita": "1.6 t",
    "urbanPct": "59%",
    "fertilityRate": "2.3",
    "migrantPct": "1.5%"
  },
  "Finland": {
    "populationDensity": "17.8 /km²",
    "co2PerCapita": "5.5 t",
    "urbanPct": "74%",
    "fertilityRate": "1.3",
    "migrantPct": "9.2%"
  },
  "France": {
    "populationDensity": "121 /km²",
    "co2PerCapita": "4.0 t",
    "urbanPct": "79%",
    "fertilityRate": "1.6",
    "migrantPct": "14%"
  },
  "Gabon": {
    "populationDensity": "7.5 /km²",
    "co2PerCapita": "2.0 t",
    "urbanPct": "92%",
    "fertilityRate": "3.6",
    "migrantPct": "18%"
  },
  "Gambia": {
    "populationDensity": "182 /km²",
    "co2PerCapita": "0.18 t",
    "urbanPct": "64%",
    "fertilityRate": "3.9",
    "migrantPct": "8.6%"
  },
  "Georgia": {
    "populationDensity": "57.1 /km²",
    "co2PerCapita": "3.6 t",
    "urbanPct": "61%",
    "fertilityRate": "1.8",
    "migrantPct": "2.1%"
  },
  "Germany": {
    "populationDensity": "232 /km²",
    "co2PerCapita": "6.9 t",
    "urbanPct": "82%",
    "fertilityRate": "1.4",
    "migrantPct": "20%"
  },
  "Ghana": {
    "populationDensity": "142 /km²",
    "co2PerCapita": "0.70 t",
    "urbanPct": "58%",
    "fertilityRate": "3.3",
    "migrantPct": "1.5%"
  },
  "Greece": {
    "populationDensity": "75.8 /km²",
    "co2PerCapita": "5.0 t",
    "urbanPct": "79%",
    "fertilityRate": "1.2",
    "migrantPct": "14%"
  },
  "Greenland": {
    "populationDensity": "0.0 /km²",
    "co2PerCapita": "10.5 t",
    "urbanPct": "88%",
    "fertilityRate": "1.7",
    "migrantPct": "10%"
  },
  "Guatemala": {
    "populationDensity": "165 /km²",
    "co2PerCapita": "1.1 t",
    "urbanPct": "56%",
    "fertilityRate": "2.3",
    "migrantPct": "0.5%"
  },
  "Guinea": {
    "populationDensity": "56.9 /km²",
    "co2PerCapita": "0.35 t",
    "urbanPct": "38%",
    "fertilityRate": "4.1",
    "migrantPct": "0.8%"
  },
  "Guyana": {
    "populationDensity": "3.6 /km²",
    "co2PerCapita": "4.6 t",
    "urbanPct": "26%",
    "fertilityRate": "2.4",
    "migrantPct": "6.5%"
  },
  "Haiti": {
    "populationDensity": "429 /km²",
    "co2PerCapita": "0.30 t",
    "urbanPct": "55%",
    "fertilityRate": "2.6",
    "migrantPct": "0.2%"
  },
  "Honduras": {
    "populationDensity": "89.3 /km²",
    "co2PerCapita": "1.1 t",
    "urbanPct": "59%",
    "fertilityRate": "2.5",
    "migrantPct": "0.4%"
  },
  "Hungary": {
    "populationDensity": "108 /km²",
    "co2PerCapita": "4.5 t",
    "urbanPct": "70%",
    "fertilityRate": "1.4",
    "migrantPct": "7.1%"
  },
  "Iceland": {
    "populationDensity": "3.8 /km²",
    "co2PerCapita": "8.5 t",
    "urbanPct": "94%",
    "fertilityRate": "1.6",
    "migrantPct": "25%"
  },
  "India": {
    "populationDensity": "424 /km²",
    "co2PerCapita": "2.2 t",
    "urbanPct": "35%",
    "fertilityRate": "2.0",
    "migrantPct": "0.3%"
  },
  "Indonesia": {
    "populationDensity": "149 /km²",
    "co2PerCapita": "2.9 t",
    "urbanPct": "59%",
    "fertilityRate": "2.1",
    "migrantPct": "0.2%"
  },
  "Iran": {
    "populationDensity": "53.8 /km²",
    "co2PerCapita": "9.1 t",
    "urbanPct": "77%",
    "fertilityRate": "1.7",
    "migrantPct": "4.2%"
  },
  "Iraq": {
    "populationDensity": "105 /km²",
    "co2PerCapita": "5.2 t",
    "urbanPct": "70%",
    "fertilityRate": "3.2",
    "migrantPct": "0.8%"
  },
  "Ireland": {
    "populationDensity": "71.4 /km²",
    "co2PerCapita": "6.0 t",
    "urbanPct": "64%",
    "fertilityRate": "1.5",
    "migrantPct": "23%"
  },
  "Israel": {
    "populationDensity": "455 /km²",
    "co2PerCapita": "5.8 t",
    "urbanPct": "92%",
    "fertilityRate": "2.9",
    "migrantPct": "22%"
  },
  "Italy": {
    "populationDensity": "196 /km²",
    "co2PerCapita": "5.1 t",
    "urbanPct": "70%",
    "fertilityRate": "1.2",
    "migrantPct": "11%"
  },
  "Jamaica": {
    "populationDensity": "273 /km²",
    "co2PerCapita": "2.8 t",
    "urbanPct": "59%",
    "fertilityRate": "1.4",
    "migrantPct": "0.8%"
  },
  "Japan": {
    "populationDensity": "325 /km²",
    "co2PerCapita": "7.8 t",
    "urbanPct": "92%",
    "fertilityRate": "1.1",
    "migrantPct": "2.8%"
  },
  "Jordan": {
    "populationDensity": "135 /km²",
    "co2PerCapita": "2.1 t",
    "urbanPct": "93%",
    "fertilityRate": "2.6",
    "migrantPct": "46%"
  },
  "Kazakhstan": {
    "populationDensity": "7.4 /km²",
    "co2PerCapita": "12.6 t",
    "urbanPct": "62%",
    "fertilityRate": "3.0",
    "migrantPct": "10%"
  },
  "Kenya": {
    "populationDensity": "91.4 /km²",
    "co2PerCapita": "0.38 t",
    "urbanPct": "32%",
    "fertilityRate": "3.2",
    "migrantPct": "1.8%"
  },
  "Kosovo": {
    "populationDensity": "182 /km²",
    "urbanPct": "50%",
    "fertilityRate": "1.5"
  },
  "Kuwait": {
    "populationDensity": "278 /km²",
    "co2PerCapita": "23.7 t",
    "urbanPct": "100%",
    "fertilityRate": "1.6",
    "migrantPct": "67%"
  },
  "Kyrgyzstan": {
    "populationDensity": "35.0 /km²",
    "co2PerCapita": "1.5 t",
    "urbanPct": "35%",
    "fertilityRate": "2.6",
    "migrantPct": "2.7%"
  },
  "Laos": {
    "populationDensity": "33.8 /km²",
    "co2PerCapita": "3.4 t",
    "urbanPct": "40%",
    "fertilityRate": "2.4",
    "migrantPct": "0.7%"
  },
  "Latvia": {
    "populationDensity": "30.8 /km²",
    "co2PerCapita": "3.6 t",
    "urbanPct": "68%",
    "fertilityRate": "1.2",
    "migrantPct": "12%"
  },
  "Lebanon": {
    "populationDensity": "500 /km²",
    "co2PerCapita": "1.9 t",
    "urbanPct": "91%",
    "fertilityRate": "2.2",
    "migrantPct": "25%"
  },
  "Lesotho": {
    "populationDensity": "66.7 /km²",
    "co2PerCapita": "0.43 t",
    "urbanPct": "44%",
    "fertilityRate": "2.7",
    "migrantPct": "0.6%"
  },
  "Liberia": {
    "populationDensity": "45.0 /km²",
    "co2PerCapita": "0.15 t",
    "urbanPct": "56%",
    "fertilityRate": "3.9",
    "migrantPct": "1.3%"
  },
  "Libya": {
    "populationDensity": "3.9 /km²",
    "co2PerCapita": "8.7 t",
    "urbanPct": "88%",
    "fertilityRate": "2.3",
    "migrantPct": "12%"
  },
  "Lithuania": {
    "populationDensity": "46.2 /km²",
    "co2PerCapita": "4.5 t",
    "urbanPct": "69%",
    "fertilityRate": "1.1",
    "migrantPct": "6.1%"
  },
  "Luxembourg": {
    "populationDensity": "227 /km²",
    "co2PerCapita": "10.6 t",
    "urbanPct": "95%",
    "fertilityRate": "1.3",
    "migrantPct": "51%"
  },
  "Madagascar": {
    "populationDensity": "54.5 /km²",
    "co2PerCapita": "0.15 t",
    "urbanPct": "32%",
    "fertilityRate": "3.9",
    "migrantPct": "0.1%"
  },
  "Malawi": {
    "populationDensity": "178 /km²",
    "co2PerCapita": "0.22 t",
    "urbanPct": "17%",
    "fertilityRate": "3.6",
    "migrantPct": "0.9%"
  },
  "Malaysia": {
    "populationDensity": "103 /km²",
    "co2PerCapita": "8.3 t",
    "urbanPct": "77%",
    "fertilityRate": "1.5",
    "migrantPct": "11%"
  },
  "Mali": {
    "populationDensity": "18.3 /km²",
    "co2PerCapita": "0.30 t",
    "urbanPct": "32%",
    "fertilityRate": "5.5",
    "migrantPct": "2.2%"
  },
  "Mauritania": {
    "populationDensity": "5.0 /km²",
    "co2PerCapita": "0.97 t",
    "urbanPct": "61%",
    "fertilityRate": "4.6",
    "migrantPct": "3.8%"
  },
  "Mexico": {
    "populationDensity": "65.5 /km²",
    "co2PerCapita": "3.6 t",
    "urbanPct": "80%",
    "fertilityRate": "1.9",
    "migrantPct": "1.3%"
  },
  "Moldova": {
    "populationDensity": "88.2 /km²",
    "co2PerCapita": "3.4 t",
    "urbanPct": "44%",
    "fertilityRate": "1.7",
    "migrantPct": "6.2%"
  },
  "Mongolia": {
    "populationDensity": "2.5 /km²",
    "co2PerCapita": "7.8 t",
    "urbanPct": "71%",
    "fertilityRate": "2.5",
    "migrantPct": "0.6%"
  },
  "Montenegro": {
    "populationDensity": "44.5 /km²",
    "urbanPct": "66%",
    "fertilityRate": "1.8",
    "migrantPct": "14%"
  },
  "Morocco": {
    "populationDensity": "82.8 /km²",
    "co2PerCapita": "1.8 t",
    "urbanPct": "63%",
    "fertilityRate": "2.2",
    "migrantPct": "0.3%"
  },
  "Mozambique": {
    "populationDensity": "42.4 /km²",
    "co2PerCapita": "0.29 t",
    "urbanPct": "36%",
    "fertilityRate": "4.7",
    "migrantPct": "1.0%"
  },
  "Myanmar": {
    "populationDensity": "75.3 /km²",
    "co2PerCapita": "0.58 t",
    "urbanPct": "30%",
    "fertilityRate": "2.1",
    "migrantPct": "0.1%"
  },
  "Namibia": {
    "populationDensity": "3.6 /km²",
    "co2PerCapita": "1.2 t",
    "urbanPct": "50%",
    "fertilityRate": "3.2",
    "migrantPct": "3.8%"
  },
  "Nepal": {
    "populationDensity": "204 /km²",
    "co2PerCapita": "0.54 t",
    "urbanPct": "67%",
    "fertilityRate": "2.0",
    "migrantPct": "1.6%"
  },
  "Netherlands": {
    "populationDensity": "429 /km²",
    "co2PerCapita": "6.6 t",
    "urbanPct": "96%",
    "fertilityRate": "1.4",
    "migrantPct": "16%"
  },
  "Nicaragua": {
    "populationDensity": "53.8 /km²",
    "co2PerCapita": "0.83 t",
    "urbanPct": "59%",
    "fertilityRate": "2.2",
    "migrantPct": "0.6%"
  },
  "Niger": {
    "populationDensity": "20.0 /km²",
    "co2PerCapita": "0.12 t",
    "urbanPct": "18%",
    "fertilityRate": "5.9",
    "migrantPct": "1.7%"
  },
  "Nigeria": {
    "populationDensity": "242 /km²",
    "co2PerCapita": "0.57 t",
    "urbanPct": "63%",
    "fertilityRate": "4.4",
    "migrantPct": "0.6%"
  },
  "Norway": {
    "populationDensity": "15.5 /km²",
    "co2PerCapita": "7.2 t",
    "urbanPct": "83%",
    "fertilityRate": "1.4",
    "migrantPct": "18%"
  },
  "Oman": {
    "populationDensity": "16.1 /km²",
    "co2PerCapita": "18.7 t",
    "urbanPct": "79%",
    "fertilityRate": "2.5",
    "migrantPct": "43%"
  },
  "Pakistan": {
    "populationDensity": "303 /km²",
    "co2PerCapita": "0.81 t",
    "urbanPct": "39%",
    "fertilityRate": "3.5",
    "migrantPct": "1.7%"
  },
  "Palestine": {
    "populationDensity": "833 /km²",
    "urbanPct": "87%",
    "fertilityRate": "3.3",
    "migrantPct": "5.0%"
  },
  "Panama": {
    "populationDensity": "53.3 /km²",
    "co2PerCapita": "2.7 t",
    "urbanPct": "66%",
    "fertilityRate": "2.1",
    "migrantPct": "11%"
  },
  "Paraguay": {
    "populationDensity": "14.7 /km²",
    "co2PerCapita": "1.2 t",
    "urbanPct": "70%",
    "fertilityRate": "2.4",
    "migrantPct": "2.6%"
  },
  "Peru": {
    "populationDensity": "26.2 /km²",
    "co2PerCapita": "2.0 t",
    "urbanPct": "85%",
    "fertilityRate": "2.0",
    "migrantPct": "5.4%"
  },
  "Philippines": {
    "populationDensity": "333 /km²",
    "co2PerCapita": "1.5 t",
    "urbanPct": "55%",
    "fertilityRate": "1.9",
    "migrantPct": "0.1%"
  },
  "Poland": {
    "populationDensity": "118 /km²",
    "co2PerCapita": "7.6 t",
    "urbanPct": "60%",
    "fertilityRate": "1.1",
    "migrantPct": "4.5%"
  },
  "Portugal": {
    "populationDensity": "120 /km²",
    "co2PerCapita": "3.3 t",
    "urbanPct": "61%",
    "fertilityRate": "1.4",
    "migrantPct": "11%"
  },
  "Qatar": {
    "populationDensity": "250 /km²",
    "co2PerCapita": "47.3 t",
    "urbanPct": "99%",
    "fertilityRate": "1.7",
    "migrantPct": "77%"
  },
  "Romania": {
    "populationDensity": "79.8 /km²",
    "co2PerCapita": "3.7 t",
    "urbanPct": "52%",
    "fertilityRate": "1.4",
    "migrantPct": "3.4%"
  },
  "Russia": {
    "populationDensity": "8.5 /km²",
    "co2PerCapita": "14.0 t",
    "urbanPct": "75%",
    "fertilityRate": "1.4",
    "migrantPct": "5.3%"
  },
  "Rwanda": {
    "populationDensity": "538 /km²",
    "co2PerCapita": "0.16 t",
    "urbanPct": "30%",
    "fertilityRate": "3.6",
    "migrantPct": "3.6%"
  },
  "Senegal": {
    "populationDensity": "96.4 /km²",
    "co2PerCapita": "0.77 t",
    "urbanPct": "55%",
    "fertilityRate": "3.8",
    "migrantPct": "1.5%"
  },
  "Serbia": {
    "populationDensity": "89.7 /km²",
    "urbanPct": "62%",
    "fertilityRate": "1.6",
    "migrantPct": "11%"
  },
  "Slovakia": {
    "populationDensity": "102 /km²",
    "co2PerCapita": "5.5 t",
    "urbanPct": "53%",
    "fertilityRate": "1.5",
    "migrantPct": "5.9%"
  },
  "Slovenia": {
    "populationDensity": "100 /km²",
    "co2PerCapita": "6.3 t",
    "urbanPct": "56%",
    "fertilityRate": "1.5",
    "migrantPct": "15%"
  },
  "Somalia": {
    "populationDensity": "31.3 /km²",
    "co2PerCapita": "0.05 t",
    "urbanPct": "55%",
    "fertilityRate": "6.0",
    "migrantPct": "0.4%"
  },
  "Spain": {
    "populationDensity": "96.8 /km²",
    "co2PerCapita": "4.5 t",
    "urbanPct": "80%",
    "fertilityRate": "1.1",
    "migrantPct": "19%"
  },
  "Sudan": {
    "populationDensity": "27.4 /km²",
    "co2PerCapita": "0.43 t",
    "urbanPct": "35%",
    "fertilityRate": "4.3",
    "migrantPct": "4.8%"
  },
  "Suriname": {
    "populationDensity": "3.8 /km²",
    "co2PerCapita": "4.1 t",
    "urbanPct": "66%",
    "fertilityRate": "2.2",
    "migrantPct": "8.2%"
  },
  "Sweden": {
    "populationDensity": "24.4 /km²",
    "co2PerCapita": "3.6 t",
    "urbanPct": "89%",
    "fertilityRate": "1.4",
    "migrantPct": "21%"
  },
  "Switzerland": {
    "populationDensity": "220 /km²",
    "co2PerCapita": "3.7 t",
    "urbanPct": "85%",
    "fertilityRate": "1.3",
    "migrantPct": "31%"
  },
  "Syria": {
    "populationDensity": "141 /km²",
    "co2PerCapita": "1.3 t",
    "urbanPct": "72%",
    "fertilityRate": "2.7",
    "migrantPct": "3.6%"
  },
  "Taiwan": {
    "populationDensity": "639 /km²"
  },
  "Tajikistan": {
    "populationDensity": "69.9 /km²",
    "co2PerCapita": "0.92 t",
    "urbanPct": "26%",
    "fertilityRate": "3.0",
    "migrantPct": "2.6%"
  },
  "Tanzania": {
    "populationDensity": "71.8 /km²",
    "co2PerCapita": "0.31 t",
    "urbanPct": "36%",
    "fertilityRate": "4.5",
    "migrantPct": "0.7%"
  },
  "Thailand": {
    "populationDensity": "129 /km²",
    "co2PerCapita": "4.0 t",
    "urbanPct": "62%",
    "fertilityRate": "1.2",
    "migrantPct": "4.4%"
  },
  "Togo": {
    "populationDensity": "140 /km²",
    "co2PerCapita": "0.28 t",
    "urbanPct": "44%",
    "fertilityRate": "4.1",
    "migrantPct": "3.0%"
  },
  "Tunisia": {
    "populationDensity": "73.2 /km²",
    "co2PerCapita": "2.6 t",
    "urbanPct": "70%",
    "fertilityRate": "1.8",
    "migrantPct": "0.5%"
  },
  "Turkey": {
    "populationDensity": "110 /km²",
    "co2PerCapita": "5.4 t",
    "urbanPct": "89%",
    "fertilityRate": "1.5",
    "migrantPct": "8.1%"
  },
  "Turkmenistan": {
    "populationDensity": "14.3 /km²",
    "co2PerCapita": "10.9 t",
    "urbanPct": "47%",
    "fertilityRate": "2.7",
    "migrantPct": "2.6%"
  },
  "Uganda": {
    "populationDensity": "190 /km²",
    "co2PerCapita": "0.17 t",
    "urbanPct": "31%",
    "fertilityRate": "4.2",
    "migrantPct": "4.1%"
  },
  "Ukraine": {
    "populationDensity": "54.6 /km²",
    "co2PerCapita": "3.1 t",
    "urbanPct": "70%",
    "fertilityRate": "1.0",
    "migrantPct": "13%"
  },
  "Uruguay": {
    "populationDensity": "16.6 /km²",
    "co2PerCapita": "2.6 t",
    "urbanPct": "96%",
    "fertilityRate": "1.4",
    "migrantPct": "4.7%"
  },
  "Uzbekistan": {
    "populationDensity": "85.0 /km²",
    "co2PerCapita": "4.1 t",
    "urbanPct": "51%",
    "fertilityRate": "3.5",
    "migrantPct": "3.2%"
  },
  "Vanuatu": {
    "populationDensity": "26.8 /km²",
    "co2PerCapita": "0.87 t",
    "urbanPct": "22%",
    "fertilityRate": "3.6",
    "migrantPct": "1.0%"
  },
  "Venezuela": {
    "populationDensity": "31.7 /km²",
    "co2PerCapita": "3.4 t",
    "urbanPct": "89%",
    "fertilityRate": "2.1",
    "migrantPct": "4.4%"
  },
  "Vietnam": {
    "populationDensity": "305 /km²",
    "co2PerCapita": "4.3 t",
    "urbanPct": "38%",
    "fertilityRate": "1.9",
    "migrantPct": "0.3%"
  },
  "Yemen": {
    "populationDensity": "62.5 /km²",
    "co2PerCapita": "0.26 t",
    "urbanPct": "37%",
    "fertilityRate": "4.5",
    "migrantPct": "1.0%"
  },
  "Zambia": {
    "populationDensity": "26.6 /km²",
    "co2PerCapita": "0.54 t",
    "urbanPct": "45%",
    "fertilityRate": "4.0",
    "migrantPct": "1.2%"
  },
  "Zimbabwe": {
    "populationDensity": "43.5 /km²",
    "co2PerCapita": "0.77 t",
    "urbanPct": "40%",
    "fertilityRate": "3.7",
    "migrantPct": "2.6%"
  }
};
