// Auto-generated from REST Countries + World Bank APIs

export interface CountryData {
  official: string;
  flag: string;
  capital: string | null;
  region: string | null;
  languages: string | null;
  currency: string | null;
  currencySymbol: string | null;
  population: string;
  area: string;
  landlocked: boolean;
  independent: boolean;
  gdp: string | null;
  gdpPerCapita: string | null;
  military: string | null;
  militaryPctGdp: string | null;
  lifeExpectancy: string | null;
  internetPct: string | null;
}

export const COUNTRY_DATA: Record<string, CountryData> = {
  Afghanistan: {
    official: 'Islamic Republic of Afghanistan',
    flag: '🇦🇫',
    capital: 'Kabul',
    region: 'Southern Asia',
    languages: 'Dari, Pashto, Turkmen',
    currency: 'Afghan afghani',
    currencySymbol: '؋',
    population: '44M',
    area: '652K km²',
    landlocked: true,
    independent: true,
    gdp: '$17B',
    gdpPerCapita: '$414',
    military: '$278M',
    militaryPctGdp: '1.8%',
    lifeExpectancy: '66.0 yr',
    internetPct: '18%',
  },
  Albania: {
    official: 'Republic of Albania',
    flag: '🇦🇱',
    capital: 'Tirana',
    region: 'Southeast Europe',
    languages: 'Albanian',
    currency: 'Albanian lek',
    currencySymbol: 'L',
    population: '2M',
    area: '29K km²',
    landlocked: false,
    independent: true,
    gdp: '$23B',
    gdpPerCapita: '$9,731',
    military: '$398M',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '79.6 yr',
    internetPct: '83%',
  },
  Algeria: {
    official: 'People\'s Democratic Republic of Algeria',
    flag: '🇩🇿',
    capital: 'Algiers',
    region: 'Northern Africa',
    languages: 'Arabic',
    currency: 'Algerian dinar',
    currencySymbol: 'د.ج',
    population: '47M',
    area: '2.4M km²',
    landlocked: false,
    independent: true,
    gdp: '$248B',
    gdpPerCapita: '$5,370',
    military: '$18B',
    militaryPctGdp: '7.4%',
    lifeExpectancy: '76.3 yr',
    internetPct: '77%',
  },
  Angola: {
    official: 'Republic of Angola',
    flag: '🇦🇴',
    capital: 'Luanda',
    region: 'Middle Africa',
    languages: 'Portuguese',
    currency: 'Angolan kwanza',
    currencySymbol: 'Kz',
    population: '36M',
    area: '1.2M km²',
    landlocked: false,
    independent: true,
    gdp: '$107B',
    gdpPerCapita: '$2,916',
    military: '$1B',
    militaryPctGdp: '1.4%',
    lifeExpectancy: '64.6 yr',
    internetPct: '45%',
  },
  Antarctica: {
    official: 'Antarctica',
    flag: '🇦🇶',
    capital: null,
    region: 'Antarctic',
    languages: null,
    currency: null,
    currencySymbol: null,
    population: '1K',
    area: '14.0M km²',
    landlocked: false,
    independent: false,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Argentina: {
    official: 'Argentine Republic',
    flag: '🇦🇷',
    capital: 'Buenos Aires',
    region: 'South America',
    languages: 'Guaraní, Spanish',
    currency: 'Argentine peso',
    currencySymbol: '$',
    population: '47M',
    area: '2.8M km²',
    landlocked: false,
    independent: true,
    gdp: '$649B',
    gdpPerCapita: '$14,262',
    military: '$5B',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '77.4 yr',
    internetPct: '89%',
  },
  Armenia: {
    official: 'Republic of Armenia',
    flag: '🇦🇲',
    capital: 'Yerevan',
    region: 'Western Asia',
    languages: 'Armenian',
    currency: 'Armenian dram',
    currencySymbol: '֏',
    population: '3M',
    area: '30K km²',
    landlocked: true,
    independent: true,
    gdp: '$24B',
    gdpPerCapita: '$8,159',
    military: '$1B',
    militaryPctGdp: '5.5%',
    lifeExpectancy: '77.5 yr',
    internetPct: '80%',
  },
  Australia: {
    official: 'Commonwealth of Australia',
    flag: '🇦🇺',
    capital: 'Canberra',
    region: 'Australia and New Zealand',
    languages: 'English',
    currency: 'Australian dollar',
    currencySymbol: '$',
    population: '28M',
    area: '7.7M km²',
    landlocked: false,
    independent: true,
    gdp: '$1.7T',
    gdpPerCapita: '$65,058',
    military: '$32B',
    militaryPctGdp: '1.9%',
    lifeExpectancy: '83.1 yr',
    internetPct: '97%',
  },
  Austria: {
    official: 'Republic of Austria',
    flag: '🇦🇹',
    capital: 'Vienna',
    region: 'Central Europe',
    languages: 'German',
    currency: 'euro',
    currencySymbol: '€',
    population: '9M',
    area: '84K km²',
    landlocked: true,
    independent: true,
    gdp: '$517B',
    gdpPerCapita: '$56,580',
    military: '$4B',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '81.5 yr',
    internetPct: '95%',
  },
  Azerbaijan: {
    official: 'Republic of Azerbaijan',
    flag: '🇦🇿',
    capital: 'Baku',
    region: 'Western Asia',
    languages: 'Azerbaijani',
    currency: 'Azerbaijani manat',
    currencySymbol: '₼',
    population: '10M',
    area: '87K km²',
    landlocked: true,
    independent: true,
    gdp: '$72B',
    gdpPerCapita: '$7,133',
    military: '$4B',
    militaryPctGdp: '4.9%',
    lifeExpectancy: '74.4 yr',
    internetPct: '89%',
  },
  Bahamas: {
    official: 'Commonwealth of the Bahamas',
    flag: '🇧🇸',
    capital: 'Nassau',
    region: 'Caribbean',
    languages: 'English',
    currency: 'Bahamian dollar',
    currencySymbol: '$',
    population: '398K',
    area: '14K km²',
    landlocked: false,
    independent: true,
    gdp: '$15B',
    gdpPerCapita: '$38,232',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '74.6 yr',
    internetPct: '95%',
  },
  Bangladesh: {
    official: 'People\'s Republic of Bangladesh',
    flag: '🇧🇩',
    capital: 'Dhaka',
    region: 'Southern Asia',
    languages: 'Bengali',
    currency: 'Bangladeshi taka',
    currencySymbol: '৳',
    population: '170M',
    area: '148K km²',
    landlocked: false,
    independent: true,
    gdp: '$437B',
    gdpPerCapita: '$2,551',
    military: '$4B',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '74.7 yr',
    internetPct: '45%',
  },
  Belarus: {
    official: 'Republic of Belarus',
    flag: '🇧🇾',
    capital: 'Minsk',
    region: 'Eastern Europe',
    languages: 'Belarusian, Russian',
    currency: 'Belarusian ruble',
    currencySymbol: 'Br',
    population: '9M',
    area: '208K km²',
    landlocked: true,
    independent: true,
    gdp: '$72B',
    gdpPerCapita: '$7,897',
    military: '$2B',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '74.2 yr',
    internetPct: '92%',
  },
  Belgium: {
    official: 'Kingdom of Belgium',
    flag: '🇧🇪',
    capital: 'Brussels',
    region: 'Western Europe',
    languages: 'German, French, Dutch',
    currency: 'euro',
    currencySymbol: '€',
    population: '12M',
    area: '31K km²',
    landlocked: false,
    independent: true,
    gdp: '$651B',
    gdpPerCapita: '$55,291',
    military: '$8B',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '82.4 yr',
    internetPct: '95%',
  },
  Belize: {
    official: 'Belize',
    flag: '🇧🇿',
    capital: 'Belmopan',
    region: 'Central America',
    languages: 'Belizean Creole, English, Spanish',
    currency: 'Belize dollar',
    currencySymbol: '$',
    population: '418K',
    area: '23K km²',
    landlocked: false,
    independent: true,
    gdp: '$3B',
    gdpPerCapita: '$7,425',
    military: '$31M',
    militaryPctGdp: '1.0%',
    lifeExpectancy: '73.6 yr',
    internetPct: '72%',
  },
  Benin: {
    official: 'Republic of Benin',
    flag: '🇧🇯',
    capital: 'Porto-Novo',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '13M',
    area: '113K km²',
    landlocked: false,
    independent: true,
    gdp: '$20B',
    gdpPerCapita: '$1,394',
    military: '$149M',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '60.8 yr',
    internetPct: '32%',
  },
  Bhutan: {
    official: 'Kingdom of Bhutan',
    flag: '🇧🇹',
    capital: 'Thimphu',
    region: 'Southern Asia',
    languages: 'Dzongkha',
    currency: 'Bhutanese ngultrum',
    currencySymbol: 'Nu.',
    population: '784K',
    area: '38K km²',
    landlocked: true,
    independent: true,
    gdp: '$3B',
    gdpPerCapita: '$3,831',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '73.0 yr',
    internetPct: '88%',
  },
  Bolivia: {
    official: 'Plurinational State of Bolivia',
    flag: '🇧🇴',
    capital: 'Sucre',
    region: 'South America',
    languages: 'Aymara, Guaraní, Quechua',
    currency: 'Bolivian boliviano',
    currencySymbol: 'Bs.',
    population: '11M',
    area: '1.1M km²',
    landlocked: true,
    independent: true,
    gdp: '$52B',
    gdpPerCapita: '$4,275',
    military: '$589M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '68.6 yr',
    internetPct: '70%',
  },
  'Bosnia and Herz.': {
    official: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    capital: 'Sarajevo',
    region: 'Southeast Europe',
    languages: 'Bosnian, Croatian, Serbian',
    currency: 'Bosnia and Herzegovina convertible mark',
    currencySymbol: 'KM',
    population: '3M',
    area: '51K km²',
    landlocked: false,
    independent: true,
    gdp: '$28B',
    gdpPerCapita: '$8,663',
    military: '$197M',
    militaryPctGdp: '0.7%',
    lifeExpectancy: '77.8 yr',
    internetPct: '83%',
  },
  Botswana: {
    official: 'Republic of Botswana',
    flag: '🇧🇼',
    capital: 'Gaborone',
    region: 'Southern Africa',
    languages: 'English, Tswana',
    currency: 'Botswana pula',
    currencySymbol: 'P',
    population: '2M',
    area: '582K km²',
    landlocked: true,
    independent: true,
    gdp: '$19B',
    gdpPerCapita: '$7,826',
    military: '$486M',
    militaryPctGdp: '2.5%',
    lifeExpectancy: '69.2 yr',
    internetPct: '81%',
  },
  Brazil: {
    official: 'Federative Republic of Brazil',
    flag: '🇧🇷',
    capital: 'Brasília',
    region: 'South America',
    languages: 'Portuguese',
    currency: 'Brazilian real',
    currencySymbol: 'R$',
    population: '213M',
    area: '8.5M km²',
    landlocked: false,
    independent: true,
    gdp: '$2.2T',
    gdpPerCapita: '$10,378',
    military: '$22B',
    militaryPctGdp: '1.0%',
    lifeExpectancy: '75.8 yr',
    internetPct: '84%',
  },
  Brunei: {
    official: 'Nation of Brunei, Abode of Peace',
    flag: '🇧🇳',
    capital: 'Bandar Seri Begawan',
    region: 'South-Eastern Asia',
    languages: 'Malay',
    currency: 'Brunei dollar',
    currencySymbol: '$',
    population: '456K',
    area: '6K km²',
    landlocked: false,
    independent: true,
    gdp: '$15B',
    gdpPerCapita: '$32,891',
    military: '$449M',
    militaryPctGdp: '3.0%',
    lifeExpectancy: '75.3 yr',
    internetPct: '99%',
  },
  Bulgaria: {
    official: 'Republic of Bulgaria',
    flag: '🇧🇬',
    capital: 'Sofia',
    region: 'Southeast Europe',
    languages: 'Bulgarian',
    currency: 'Bulgarian lev',
    currencySymbol: 'лв',
    population: '6M',
    area: '111K km²',
    landlocked: false,
    independent: true,
    gdp: '$102B',
    gdpPerCapita: '$15,853',
    military: '$2B',
    militaryPctGdp: '1.9%',
    lifeExpectancy: '75.7 yr',
    internetPct: '80%',
  },
  'Burkina Faso': {
    official: 'Burkina Faso',
    flag: '🇧🇫',
    capital: 'Ouagadougou',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '24M',
    area: '273K km²',
    landlocked: true,
    independent: true,
    gdp: '$20B',
    gdpPerCapita: '$873',
    military: '$827M',
    militaryPctGdp: '4.1%',
    lifeExpectancy: '61.1 yr',
    internetPct: '17%',
  },
  Burundi: {
    official: 'Republic of Burundi',
    flag: '🇧🇮',
    capital: 'Gitega',
    region: 'Eastern Africa',
    languages: 'French, Kirundi',
    currency: 'Burundian franc',
    currencySymbol: 'Fr',
    population: '12M',
    area: '28K km²',
    landlocked: true,
    independent: true,
    gdp: '$3B',
    gdpPerCapita: '$251',
    military: '$145M',
    militaryPctGdp: '3.4%',
    lifeExpectancy: '63.7 yr',
    internetPct: '11%',
  },
  Cambodia: {
    official: 'Kingdom of Cambodia',
    flag: '🇰🇭',
    capital: 'Phnom Penh',
    region: 'South-Eastern Asia',
    languages: 'Khmer',
    currency: 'Cambodian riel',
    currencySymbol: '៛',
    population: '18M',
    area: '181K km²',
    landlocked: false,
    independent: true,
    gdp: '$42B',
    gdpPerCapita: '$2,430',
    military: '$668M',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '70.7 yr',
    internetPct: '61%',
  },
  Cameroon: {
    official: 'Republic of Cameroon',
    flag: '🇨🇲',
    capital: 'Yaoundé',
    region: 'Middle Africa',
    languages: 'English, French',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '29M',
    area: '475K km²',
    landlocked: false,
    independent: true,
    gdp: '$49B',
    gdpPerCapita: '$1,720',
    military: '$457M',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '63.7 yr',
    internetPct: '42%',
  },
  Canada: {
    official: 'Canada',
    flag: '🇨🇦',
    capital: 'Ottawa',
    region: 'North America',
    languages: 'English, French',
    currency: 'Canadian dollar',
    currencySymbol: '$',
    population: '42M',
    area: '10.0M km²',
    landlocked: false,
    independent: true,
    gdp: '$2.2T',
    gdpPerCapita: '$54,220',
    military: '$27B',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '81.6 yr',
    internetPct: '94%',
  },
  'Central African Rep.': {
    official: 'Central African Republic',
    flag: '🇨🇫',
    capital: 'Bangui',
    region: 'Middle Africa',
    languages: 'French, Sango',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '6M',
    area: '623K km²',
    landlocked: true,
    independent: true,
    gdp: '$3B',
    gdpPerCapita: '$496',
    military: '$63M',
    militaryPctGdp: '2.4%',
    lifeExpectancy: '57.4 yr',
    internetPct: null,
  },
  Chad: {
    official: 'Republic of Chad',
    flag: '🇹🇩',
    capital: 'N\'Djamena',
    region: 'Middle Africa',
    languages: 'Arabic, French',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '19M',
    area: '1.3M km²',
    landlocked: true,
    independent: true,
    gdp: '$18B',
    gdpPerCapita: '$949',
    military: '$373M',
    militaryPctGdp: '2.1%',
    lifeExpectancy: '55.1 yr',
    internetPct: '13%',
  },
  Chile: {
    official: 'Republic of Chile',
    flag: '🇨🇱',
    capital: 'Santiago',
    region: 'South America',
    languages: 'Spanish',
    currency: 'Chilean peso',
    currencySymbol: '$',
    population: '20M',
    area: '756K km²',
    landlocked: false,
    independent: true,
    gdp: '$336B',
    gdpPerCapita: '$17,067',
    military: '$5B',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '81.2 yr',
    internetPct: '94%',
  },
  China: {
    official: 'People\'s Republic of China',
    flag: '🇨🇳',
    capital: 'Beijing',
    region: 'Eastern Asia',
    languages: 'Chinese',
    currency: 'Chinese yuan',
    currencySymbol: '¥',
    population: '1.4B',
    area: '9.7M km²',
    landlocked: false,
    independent: true,
    gdp: '$18.3T',
    gdpPerCapita: '$12,951',
    military: '$297B',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '78.0 yr',
    internetPct: '91%',
  },
  Colombia: {
    official: 'Republic of Colombia',
    flag: '🇨🇴',
    capital: 'Bogotá',
    region: 'South America',
    languages: 'Spanish',
    currency: 'Colombian peso',
    currencySymbol: '$',
    population: '53M',
    area: '1.1M km²',
    landlocked: false,
    independent: true,
    gdp: '$366B',
    gdpPerCapita: '$7,001',
    military: '$11B',
    militaryPctGdp: '3.0%',
    lifeExpectancy: '77.7 yr',
    internetPct: '77%',
  },
  Congo: {
    official: 'Republic of the Congo',
    flag: '🇨🇬',
    capital: 'Brazzaville',
    region: 'Middle Africa',
    languages: 'French, Kikongo, Lingala',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '6M',
    area: '342K km²',
    landlocked: false,
    independent: true,
    gdp: '$15B',
    gdpPerCapita: '$2,478',
    military: '$285M',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '65.8 yr',
    internetPct: '38%',
  },
  'Costa Rica': {
    official: 'Republic of Costa Rica',
    flag: '🇨🇷',
    capital: 'San José',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'Costa Rican colón',
    currencySymbol: '₡',
    population: '5M',
    area: '51K km²',
    landlocked: false,
    independent: true,
    gdp: '$86B',
    gdpPerCapita: '$16,942',
    military: '$0',
    militaryPctGdp: null,
    lifeExpectancy: '80.8 yr',
    internetPct: '85%',
  },
  Croatia: {
    official: 'Republic of Croatia',
    flag: '🇭🇷',
    capital: 'Zagreb',
    region: 'Southeast Europe',
    languages: 'Croatian',
    currency: 'euro',
    currencySymbol: '€',
    population: '4M',
    area: '57K km²',
    landlocked: false,
    independent: true,
    gdp: '$86B',
    gdpPerCapita: '$22,184',
    military: '$1B',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '78.5 yr',
    internetPct: '83%',
  },
  Cuba: {
    official: 'Republic of Cuba',
    flag: '🇨🇺',
    capital: 'Havana',
    region: 'Caribbean',
    languages: 'Spanish',
    currency: 'Cuban convertible peso',
    currencySymbol: '$',
    population: '10M',
    area: '110K km²',
    landlocked: false,
    independent: true,
    gdp: '$107B',
    gdpPerCapita: '$9,605',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '78.1 yr',
    internetPct: '71%',
  },
  Cyprus: {
    official: 'Republic of Cyprus',
    flag: '🇨🇾',
    capital: 'Nicosia',
    region: 'Southern Europe',
    languages: 'Greek, Turkish',
    currency: 'euro',
    currencySymbol: '€',
    population: '1M',
    area: '9K km²',
    landlocked: false,
    independent: true,
    gdp: '$35B',
    gdpPerCapita: '$36,624',
    military: '$559M',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '81.6 yr',
    internetPct: '91%',
  },
  Czechia: {
    official: 'Czech Republic',
    flag: '🇨🇿',
    capital: 'Prague',
    region: 'Central Europe',
    languages: 'Czech, Slovak',
    currency: 'Czech koruna',
    currencySymbol: 'Kč',
    population: '11M',
    area: '79K km²',
    landlocked: true,
    independent: true,
    gdp: '$345B',
    gdpPerCapita: '$31,762',
    military: '$5B',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '79.9 yr',
    internetPct: '86%',
  },
  "Côte d'Ivoire": {
    official: 'Republic of Côte d\'Ivoire',
    flag: '🇨🇮',
    capital: 'Yamoussoukro',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '32M',
    area: '322K km²',
    landlocked: false,
    independent: true,
    gdp: '$81B',
    gdpPerCapita: '$2,592',
    military: '$682M',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '61.9 yr',
    internetPct: '41%',
  },
  'Dem. Rep. Congo': {
    official: 'Democratic Republic of the Congo',
    flag: '🇨🇩',
    capital: 'Kinshasa',
    region: 'Middle Africa',
    languages: 'French, Kikongo, Lingala',
    currency: 'Congolese franc',
    currencySymbol: 'FC',
    population: '113M',
    area: '2.3M km²',
    landlocked: false,
    independent: true,
    gdp: '$70B',
    gdpPerCapita: '$660',
    military: '$794M',
    militaryPctGdp: '1.1%',
    lifeExpectancy: '61.9 yr',
    internetPct: '31%',
  },
  Denmark: {
    official: 'Kingdom of Denmark',
    flag: '🇩🇰',
    capital: 'Copenhagen',
    region: 'Northern Europe',
    languages: 'Danish',
    currency: 'Danish krone',
    currencySymbol: 'kr',
    population: '6M',
    area: '43K km²',
    landlocked: false,
    independent: true,
    gdp: '$405B',
    gdpPerCapita: '$68,044',
    military: '$8B',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '81.9 yr',
    internetPct: '99%',
  },
  Djibouti: {
    official: 'Republic of Djibouti',
    flag: '🇩🇯',
    capital: 'Djibouti',
    region: 'Eastern Africa',
    languages: 'Arabic, French',
    currency: 'Djiboutian franc',
    currencySymbol: 'Fr',
    population: '1M',
    area: '23K km²',
    landlocked: false,
    independent: true,
    gdp: '$4B',
    gdpPerCapita: '$3,381',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '66.0 yr',
    internetPct: '65%',
  },
  'Dominican Rep.': {
    official: 'Dominican Republic',
    flag: '🇩🇴',
    capital: 'Santo Domingo',
    region: 'Caribbean',
    languages: 'Spanish',
    currency: 'Dominican peso',
    currencySymbol: '$',
    population: '11M',
    area: '49K km²',
    landlocked: false,
    independent: true,
    gdp: '$120B',
    gdpPerCapita: '$10,630',
    military: '$946M',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '73.7 yr',
    internetPct: '85%',
  },
  Ecuador: {
    official: 'Republic of Ecuador',
    flag: '🇪🇨',
    capital: 'Quito',
    region: 'South America',
    languages: 'Spanish',
    currency: 'United States dollar',
    currencySymbol: '$',
    population: '18M',
    area: '277K km²',
    landlocked: false,
    independent: true,
    gdp: '$121B',
    gdpPerCapita: '$6,738',
    military: '$3B',
    militaryPctGdp: '2.3%',
    lifeExpectancy: '77.4 yr',
    internetPct: '73%',
  },
  Egypt: {
    official: 'Arab Republic of Egypt',
    flag: '🇪🇬',
    capital: 'Cairo',
    region: 'Northern Africa',
    languages: 'Arabic',
    currency: 'Egyptian pound',
    currencySymbol: '£',
    population: '107M',
    area: '1.0M km²',
    landlocked: false,
    independent: true,
    gdp: '$396B',
    gdpPerCapita: '$3,457',
    military: '$3B',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '71.6 yr',
    internetPct: '73%',
  },
  'El Salvador': {
    official: 'Republic of El Salvador',
    flag: '🇸🇻',
    capital: 'San Salvador',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'United States dollar',
    currencySymbol: '$',
    population: '6M',
    area: '21K km²',
    landlocked: false,
    independent: true,
    gdp: '$34B',
    gdpPerCapita: '$5,365',
    military: '$455M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '72.1 yr',
    internetPct: '68%',
  },
  'Eq. Guinea': {
    official: 'Republic of Equatorial Guinea',
    flag: '🇬🇶',
    capital: 'Ciudad de la Paz',
    region: 'Middle Africa',
    languages: 'French, Portuguese, Spanish',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '2M',
    area: '28K km²',
    landlocked: false,
    independent: true,
    gdp: '$12B',
    gdpPerCapita: '$6,678',
    military: '$162M',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '63.7 yr',
    internetPct: '60%',
  },
  Eritrea: {
    official: 'State of Eritrea',
    flag: '🇪🇷',
    capital: 'Asmara',
    region: 'Eastern Africa',
    languages: 'Arabic, English, Tigrinya',
    currency: 'Eritrean nakfa',
    currencySymbol: 'Nfk',
    population: '4M',
    area: '118K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '68.6 yr',
    internetPct: '20%',
  },
  Estonia: {
    official: 'Republic of Estonia',
    flag: '🇪🇪',
    capital: 'Tallinn',
    region: 'Northern Europe',
    languages: 'Estonian',
    currency: 'euro',
    currencySymbol: '€',
    population: '1M',
    area: '45K km²',
    landlocked: false,
    independent: true,
    gdp: '$41B',
    gdpPerCapita: '$30,264',
    military: '$1B',
    militaryPctGdp: '3.0%',
    lifeExpectancy: '78.5 yr',
    internetPct: '93%',
  },
  Ethiopia: {
    official: 'Federal Democratic Republic of Ethiopia',
    flag: '🇪🇹',
    capital: 'Addis Ababa',
    region: 'Eastern Africa',
    languages: 'Amharic',
    currency: 'Ethiopian birr',
    currencySymbol: 'Br',
    population: '112M',
    area: '1.1M km²',
    landlocked: true,
    independent: true,
    gdp: '$136B',
    gdpPerCapita: '$1,056',
    military: '$1B',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '67.3 yr',
    internetPct: '17%',
  },
  'Falkland Is.': {
    official: 'Falkland Islands',
    flag: '🇫🇰',
    capital: 'Stanley',
    region: 'South America',
    languages: 'English',
    currency: 'Falkland Islands pound',
    currencySymbol: '£',
    population: '4K',
    area: '12K km²',
    landlocked: false,
    independent: false,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Fiji: {
    official: 'Republic of Fiji',
    flag: '🇫🇯',
    capital: 'Suva',
    region: 'Melanesia',
    languages: 'English, Fijian, Fiji Hindi',
    currency: 'Fijian dollar',
    currencySymbol: '$',
    population: '901K',
    area: '18K km²',
    landlocked: false,
    independent: true,
    gdp: '$5B',
    gdpPerCapita: '$5,926',
    military: '$73M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '67.3 yr',
    internetPct: '79%',
  },
  Finland: {
    official: 'Republic of Finland',
    flag: '🇫🇮',
    capital: 'Helsinki',
    region: 'Northern Europe',
    languages: 'Finnish, Swedish',
    currency: 'euro',
    currencySymbol: '€',
    population: '6M',
    area: '338K km²',
    landlocked: false,
    independent: true,
    gdp: '$295B',
    gdpPerCapita: '$52,834',
    military: '$6B',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '81.7 yr',
    internetPct: '94%',
  },
  France: {
    official: 'French Republic',
    flag: '🇫🇷',
    capital: 'Paris',
    region: 'Western Europe',
    languages: 'French',
    currency: 'euro',
    currencySymbol: '€',
    population: '66M',
    area: '544K km²',
    landlocked: false,
    independent: true,
    gdp: '$3.1T',
    gdpPerCapita: '$44,700',
    military: '$59B',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '82.9 yr',
    internetPct: '87%',
  },
  Gabon: {
    official: 'Gabonese Republic',
    flag: '🇬🇦',
    capital: 'Libreville',
    region: 'Middle Africa',
    languages: 'French',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    population: '2M',
    area: '268K km²',
    landlocked: false,
    independent: true,
    gdp: '$19B',
    gdpPerCapita: '$7,803',
    military: '$265M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '68.3 yr',
    internetPct: '72%',
  },
  Gambia: {
    official: 'Republic of the Gambia',
    flag: '🇬🇲',
    capital: 'Banjul',
    region: 'Western Africa',
    languages: 'English',
    currency: 'dalasi',
    currencySymbol: 'D',
    population: '2M',
    area: '11K km²',
    landlocked: false,
    independent: true,
    gdp: '$2B',
    gdpPerCapita: '$883',
    military: '$14M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '65.9 yr',
    internetPct: '46%',
  },
  Georgia: {
    official: 'Georgia',
    flag: '🇬🇪',
    capital: 'Tbilisi',
    region: 'Western Asia',
    languages: 'Georgian',
    currency: 'lari',
    currencySymbol: '₾',
    population: '4M',
    area: '70K km²',
    landlocked: false,
    independent: true,
    gdp: '$31B',
    gdpPerCapita: '$8,284',
    military: '$508M',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '74.5 yr',
    internetPct: '82%',
  },
  Germany: {
    official: 'Federal Republic of Germany',
    flag: '🇩🇪',
    capital: 'Berlin',
    region: 'Western Europe',
    languages: 'German',
    currency: 'euro',
    currencySymbol: '€',
    population: '83M',
    area: '357K km²',
    landlocked: false,
    independent: true,
    gdp: '$4.6T',
    gdpPerCapita: '$54,777',
    military: '$67B',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '80.5 yr',
    internetPct: '92%',
  },
  Ghana: {
    official: 'Republic of Ghana',
    flag: '🇬🇭',
    capital: 'Accra',
    region: 'Western Africa',
    languages: 'English',
    currency: 'Ghanaian cedi',
    currencySymbol: '₵',
    population: '34M',
    area: '239K km²',
    landlocked: false,
    independent: true,
    gdp: '$81B',
    gdpPerCapita: '$2,384',
    military: '$285M',
    militaryPctGdp: '0.4%',
    lifeExpectancy: '65.5 yr',
    internetPct: '70%',
  },
  Greece: {
    official: 'Hellenic Republic',
    flag: '🇬🇷',
    capital: 'Athens',
    region: 'Southern Europe',
    languages: 'Greek',
    currency: 'euro',
    currencySymbol: '€',
    population: '10M',
    area: '132K km²',
    landlocked: false,
    independent: true,
    gdp: '$243B',
    gdpPerCapita: '$23,344',
    military: '$7B',
    militaryPctGdp: '2.9%',
    lifeExpectancy: '81.5 yr',
    internetPct: '85%',
  },
  Greenland: {
    official: 'Greenland',
    flag: '🇬🇱',
    capital: 'Nuuk',
    region: 'North America',
    languages: 'Greenlandic',
    currency: 'krone',
    currencySymbol: 'kr.',
    population: '57K',
    area: '2.2M km²',
    landlocked: false,
    independent: false,
    gdp: '$3B',
    gdpPerCapita: '$58,499',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '71.5 yr',
    internetPct: null,
  },
  Guatemala: {
    official: 'Republic of Guatemala',
    flag: '🇬🇹',
    capital: 'Guatemala City',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'Guatemalan quetzal',
    currencySymbol: 'Q',
    population: '18M',
    area: '109K km²',
    landlocked: false,
    independent: true,
    gdp: '$104B',
    gdpPerCapita: '$5,758',
    military: '$438M',
    militaryPctGdp: '0.4%',
    lifeExpectancy: '72.6 yr',
    internetPct: '56%',
  },
  Guinea: {
    official: 'Republic of Guinea',
    flag: '🇬🇳',
    capital: 'Conakry',
    region: 'Western Africa',
    languages: 'French',
    currency: 'Guinean franc',
    currencySymbol: 'Fr',
    population: '14M',
    area: '246K km²',
    landlocked: false,
    independent: true,
    gdp: '$22B',
    gdpPerCapita: '$1,555',
    military: '$505M',
    militaryPctGdp: '2.1%',
    lifeExpectancy: '60.7 yr',
    internetPct: '27%',
  },
  'Guinea-Bissau': {
    official: 'Republic of Guinea-Bissau',
    flag: '🇬🇼',
    capital: 'Bissau',
    region: 'Western Africa',
    languages: 'Portuguese, Upper Guinea Creole',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '2M',
    area: '36K km²',
    landlocked: false,
    independent: true,
    gdp: '$2B',
    gdpPerCapita: '$988',
    military: '$25M',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '64.1 yr',
    internetPct: '32%',
  },
  Guyana: {
    official: 'Co-operative Republic of Guyana',
    flag: '🇬🇾',
    capital: 'Georgetown',
    region: 'South America',
    languages: 'English',
    currency: 'Guyanese dollar',
    currencySymbol: '$',
    population: '773K',
    area: '215K km²',
    landlocked: false,
    independent: true,
    gdp: '$17B',
    gdpPerCapita: '$20,474',
    military: '$110M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '70.2 yr',
    internetPct: '82%',
  },
  Haiti: {
    official: 'Republic of Haiti',
    flag: '🇭🇹',
    capital: 'Port-au-Prince',
    region: 'Caribbean',
    languages: 'French, Haitian Creole',
    currency: 'Haitian gourde',
    currencySymbol: 'G',
    population: '12M',
    area: '28K km²',
    landlocked: false,
    independent: true,
    gdp: '$20B',
    gdpPerCapita: '$1,706',
    military: '$12M',
    militaryPctGdp: '0.1%',
    lifeExpectancy: '64.9 yr',
    internetPct: null,
  },
  Honduras: {
    official: 'Republic of Honduras',
    flag: '🇭🇳',
    capital: 'Tegucigalpa',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'Honduran lempira',
    currencySymbol: 'L',
    population: '10M',
    area: '112K km²',
    landlocked: false,
    independent: true,
    gdp: '$34B',
    gdpPerCapita: '$3,227',
    military: '$523M',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '72.9 yr',
    internetPct: '58%',
  },
  Hungary: {
    official: 'Hungary',
    flag: '🇭🇺',
    capital: 'Budapest',
    region: 'Central Europe',
    languages: 'Hungarian',
    currency: 'Hungarian forint',
    currencySymbol: 'Ft',
    population: '10M',
    area: '93K km²',
    landlocked: true,
    independent: true,
    gdp: '$213B',
    gdpPerCapita: '$22,231',
    military: '$4B',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '76.8 yr',
    internetPct: '91%',
  },
  Iceland: {
    official: 'Iceland',
    flag: '🇮🇸',
    capital: 'Reykjavik',
    region: 'Northern Europe',
    languages: 'Icelandic',
    currency: 'Icelandic króna',
    currencySymbol: 'kr',
    population: '392K',
    area: '103K km²',
    landlocked: false,
    independent: true,
    gdp: '$32B',
    gdpPerCapita: '$82,139',
    military: '$0',
    militaryPctGdp: null,
    lifeExpectancy: '82.6 yr',
    internetPct: '100%',
  },
  India: {
    official: 'Republic of India',
    flag: '🇮🇳',
    capital: 'New Delhi',
    region: 'Southern Asia',
    languages: 'English, Hindi, Tamil',
    currency: 'Indian rupee',
    currencySymbol: '₹',
    population: '1.4B',
    area: '3.3M km²',
    landlocked: false,
    independent: true,
    gdp: '$3.6T',
    gdpPerCapita: '$2,530',
    military: '$82B',
    militaryPctGdp: '2.4%',
    lifeExpectancy: '72.0 yr',
    internetPct: '56%',
  },
  Indonesia: {
    official: 'Republic of Indonesia',
    flag: '🇮🇩',
    capital: 'Jakarta',
    region: 'South-Eastern Asia',
    languages: 'Indonesian',
    currency: 'Indonesian rupiah',
    currencySymbol: 'Rp',
    population: '284M',
    area: '1.9M km²',
    landlocked: false,
    independent: true,
    gdp: '$1.4T',
    gdpPerCapita: '$4,876',
    military: '$11B',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '71.1 yr',
    internetPct: '69%',
  },
  Iran: {
    official: 'Islamic Republic of Iran',
    flag: '🇮🇷',
    capital: 'Tehran',
    region: 'Southern Asia',
    languages: 'Persian (Farsi)',
    currency: 'Iranian rial',
    currencySymbol: '﷼',
    population: '86M',
    area: '1.6M km²',
    landlocked: false,
    independent: true,
    gdp: '$458B',
    gdpPerCapita: '$5,049',
    military: '$7B',
    militaryPctGdp: '2.4%',
    lifeExpectancy: '77.7 yr',
    internetPct: '80%',
  },
  Iraq: {
    official: 'Republic of Iraq',
    flag: '🇮🇶',
    capital: 'Baghdad',
    region: 'Western Asia',
    languages: 'Arabic, Aramaic, Sorani',
    currency: 'Iraqi dinar',
    currencySymbol: 'ع.د',
    population: '46M',
    area: '438K km²',
    landlocked: false,
    independent: true,
    gdp: '$269B',
    gdpPerCapita: '$5,965',
    military: '$6B',
    militaryPctGdp: '2.3%',
    lifeExpectancy: '72.3 yr',
    internetPct: '82%',
  },
  Ireland: {
    official: 'Republic of Ireland',
    flag: '🇮🇪',
    capital: 'Dublin',
    region: 'Northern Europe',
    languages: 'English, Irish',
    currency: 'euro',
    currencySymbol: '€',
    population: '5M',
    area: '70K km²',
    landlocked: false,
    independent: true,
    gdp: '$567B',
    gdpPerCapita: '$106,819',
    military: '$1B',
    militaryPctGdp: '0.2%',
    lifeExpectancy: '82.9 yr',
    internetPct: '96%',
  },
  Israel: {
    official: 'State of Israel',
    flag: '🇮🇱',
    capital: 'Jerusalem',
    region: 'Western Asia',
    languages: 'Arabic, Hebrew',
    currency: 'Israeli new shekel',
    currencySymbol: '₪',
    population: '10M',
    area: '22K km²',
    landlocked: false,
    independent: true,
    gdp: '$512B',
    gdpPerCapita: '$52,004',
    military: '$27B',
    militaryPctGdp: '5.4%',
    lifeExpectancy: '83.2 yr',
    internetPct: '87%',
  },
  Italy: {
    official: 'Italian Republic',
    flag: '🇮🇹',
    capital: 'Rome',
    region: 'Southern Europe',
    languages: 'Italian, Catalan',
    currency: 'euro',
    currencySymbol: '€',
    population: '59M',
    area: '301K km²',
    landlocked: false,
    independent: true,
    gdp: '$2.3T',
    gdpPerCapita: '$39,277',
    military: '$37B',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '83.7 yr',
    internetPct: '87%',
  },
  Jamaica: {
    official: 'Jamaica',
    flag: '🇯🇲',
    capital: 'Kingston',
    region: 'Caribbean',
    languages: 'English, Jamaican Patois',
    currency: 'Jamaican dollar',
    currencySymbol: '$',
    population: '3M',
    area: '11K km²',
    landlocked: false,
    independent: true,
    gdp: '$21B',
    gdpPerCapita: '$7,542',
    military: '$230M',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '71.5 yr',
    internetPct: '89%',
  },
  Japan: {
    official: 'Japan',
    flag: '🇯🇵',
    capital: 'Tokyo',
    region: 'Eastern Asia',
    languages: 'Japanese',
    currency: 'Japanese yen',
    currencySymbol: '¥',
    population: '123M',
    area: '378K km²',
    landlocked: false,
    independent: true,
    gdp: '$4.2T',
    gdpPerCapita: '$33,836',
    military: '$48B',
    militaryPctGdp: '1.1%',
    lifeExpectancy: '84.0 yr',
    internetPct: '87%',
  },
  Jordan: {
    official: 'Hashemite Kingdom of Jordan',
    flag: '🇯🇴',
    capital: 'Amman',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Jordanian dinar',
    currencySymbol: 'د.ا',
    population: '12M',
    area: '89K km²',
    landlocked: false,
    independent: true,
    gdp: '$51B',
    gdpPerCapita: '$4,466',
    military: '$2B',
    militaryPctGdp: '4.8%',
    lifeExpectancy: '77.8 yr',
    internetPct: '93%',
  },
  Kazakhstan: {
    official: 'Republic of Kazakhstan',
    flag: '🇰🇿',
    capital: 'Astana',
    region: 'Central Asia',
    languages: 'Kazakh, Russian',
    currency: 'Kazakhstani tenge',
    currencySymbol: '₸',
    population: '20M',
    area: '2.7M km²',
    landlocked: true,
    independent: true,
    gdp: '$262B',
    gdpPerCapita: '$12,879',
    military: '$1B',
    militaryPctGdp: '0.4%',
    lifeExpectancy: '74.4 yr',
    internetPct: '93%',
  },
  Kenya: {
    official: 'Republic of Kenya',
    flag: '🇰🇪',
    capital: 'Nairobi',
    region: 'Eastern Africa',
    languages: 'English, Swahili',
    currency: 'Kenyan shilling',
    currencySymbol: 'Sh',
    population: '53M',
    area: '580K km²',
    landlocked: false,
    independent: true,
    gdp: '$108B',
    gdpPerCapita: '$1,943',
    military: '$1B',
    militaryPctGdp: '1.0%',
    lifeExpectancy: '63.6 yr',
    internetPct: '35%',
  },
  Kosovo: {
    official: 'Republic of Kosovo',
    flag: '🇽🇰',
    capital: 'Pristina',
    region: 'Southeast Europe',
    languages: 'Albanian, Serbian',
    currency: 'euro',
    currencySymbol: '€',
    population: '2M',
    area: '11K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Kuwait: {
    official: 'State of Kuwait',
    flag: '🇰🇼',
    capital: 'Kuwait City',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Kuwaiti dinar',
    currencySymbol: 'د.ك',
    population: '5M',
    area: '18K km²',
    landlocked: false,
    independent: true,
    gdp: '$165B',
    gdpPerCapita: '$34,076',
    military: '$8B',
    militaryPctGdp: '4.8%',
    lifeExpectancy: '83.2 yr',
    internetPct: '100%',
  },
  Kyrgyzstan: {
    official: 'Kyrgyz Republic',
    flag: '🇰🇬',
    capital: 'Bishkek',
    region: 'Central Asia',
    languages: 'Kyrgyz, Russian',
    currency: 'Kyrgyzstani som',
    currencySymbol: 'с',
    population: '7M',
    area: '200K km²',
    landlocked: true,
    independent: true,
    gdp: '$15B',
    gdpPerCapita: '$2,138',
    military: '$484M',
    militaryPctGdp: '3.5%',
    lifeExpectancy: '72.2 yr',
    internetPct: '88%',
  },
  Laos: {
    official: 'Lao People\'s Democratic Republic',
    flag: '🇱🇦',
    capital: 'Vientiane',
    region: 'South-Eastern Asia',
    languages: 'Lao',
    currency: 'Lao kip',
    currencySymbol: '₭',
    population: '8M',
    area: '237K km²',
    landlocked: true,
    independent: true,
    gdp: '$16B',
    gdpPerCapita: '$2,067',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '69.0 yr',
    internetPct: '64%',
  },
  Latvia: {
    official: 'Republic of Latvia',
    flag: '🇱🇻',
    capital: 'Riga',
    region: 'Northern Europe',
    languages: 'Latvian',
    currency: 'euro',
    currencySymbol: '€',
    population: '2M',
    area: '65K km²',
    landlocked: false,
    independent: true,
    gdp: '$43B',
    gdpPerCapita: '$22,710',
    military: '$1B',
    militaryPctGdp: '3.0%',
    lifeExpectancy: '75.7 yr',
    internetPct: '92%',
  },
  Lebanon: {
    official: 'Lebanese Republic',
    flag: '🇱🇧',
    capital: 'Beirut',
    region: 'Western Asia',
    languages: 'Arabic, French',
    currency: 'Lebanese pound',
    currencySymbol: 'ل.ل',
    population: '5M',
    area: '10K km²',
    landlocked: false,
    independent: true,
    gdp: '$20B',
    gdpPerCapita: '$3,478',
    military: '$286M',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '77.8 yr',
    internetPct: '83%',
  },
  Lesotho: {
    official: 'Kingdom of Lesotho',
    flag: '🇱🇸',
    capital: 'Maseru',
    region: 'Southern Africa',
    languages: 'English, Sotho',
    currency: 'Lesotho loti',
    currencySymbol: 'L',
    population: '2M',
    area: '30K km²',
    landlocked: true,
    independent: true,
    gdp: '$2B',
    gdpPerCapita: '$916',
    military: '$34M',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '57.4 yr',
    internetPct: '48%',
  },
  Liberia: {
    official: 'Republic of Liberia',
    flag: '🇱🇷',
    capital: 'Monrovia',
    region: 'Western Africa',
    languages: 'English',
    currency: 'Liberian dollar',
    currencySymbol: '$',
    population: '5M',
    area: '111K km²',
    landlocked: false,
    independent: true,
    gdp: '$4B',
    gdpPerCapita: '$799',
    military: '$63M',
    militaryPctGdp: '1.4%',
    lifeExpectancy: '62.2 yr',
    internetPct: '23%',
  },
  Libya: {
    official: 'State of Libya',
    flag: '🇱🇾',
    capital: 'Tripoli',
    region: 'Northern Africa',
    languages: 'Arabic',
    currency: 'Libyan dinar',
    currencySymbol: 'ل.د',
    population: '7M',
    area: '1.8M km²',
    landlocked: false,
    independent: true,
    gdp: '$44B',
    gdpPerCapita: '$6,027',
    military: '$2B',
    militaryPctGdp: '5.3%',
    lifeExpectancy: '69.3 yr',
    internetPct: '88%',
  },
  Lithuania: {
    official: 'Republic of Lithuania',
    flag: '🇱🇹',
    capital: 'Vilnius',
    region: 'Northern Europe',
    languages: 'Lithuanian',
    currency: 'euro',
    currencySymbol: '€',
    population: '3M',
    area: '65K km²',
    landlocked: false,
    independent: true,
    gdp: '$80B',
    gdpPerCapita: '$27,786',
    military: '$2B',
    militaryPctGdp: '2.7%',
    lifeExpectancy: '77.0 yr',
    internetPct: '89%',
  },
  Luxembourg: {
    official: 'Grand Duchy of Luxembourg',
    flag: '🇱🇺',
    capital: 'Luxembourg',
    region: 'Western Europe',
    languages: 'German, French, Luxembourgish',
    currency: 'euro',
    currencySymbol: '€',
    population: '682K',
    area: '3K km²',
    landlocked: true,
    independent: true,
    gdp: '$89B',
    gdpPerCapita: '$133,231',
    military: '$662M',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '83.4 yr',
    internetPct: '99%',
  },
  Macedonia: {
    official: 'Republic of North Macedonia',
    flag: '🇲🇰',
    capital: 'Skopje',
    region: 'Southeast Europe',
    languages: 'Macedonian',
    currency: 'denar',
    currencySymbol: 'den',
    population: '2M',
    area: '26K km²',
    landlocked: true,
    independent: true,
    gdp: '$16B',
    gdpPerCapita: '$8,674',
    military: '$267M',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '75.3 yr',
    internetPct: '87%',
  },
  Madagascar: {
    official: 'Republic of Madagascar',
    flag: '🇲🇬',
    capital: 'Antananarivo',
    region: 'Eastern Africa',
    languages: 'French, Malagasy',
    currency: 'Malagasy ariary',
    currencySymbol: 'Ar',
    population: '32M',
    area: '587K km²',
    landlocked: false,
    independent: true,
    gdp: '$16B',
    gdpPerCapita: '$509',
    military: '$102M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '63.6 yr',
    internetPct: '20%',
  },
  Malawi: {
    official: 'Republic of Malawi',
    flag: '🇲🇼',
    capital: 'Lilongwe',
    region: 'Eastern Africa',
    languages: 'English, Chewa',
    currency: 'Malawian kwacha',
    currencySymbol: 'MK',
    population: '21M',
    area: '118K km²',
    landlocked: true,
    independent: true,
    gdp: '$13B',
    gdpPerCapita: '$633',
    military: '$150M',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '67.4 yr',
    internetPct: '18%',
  },
  Malaysia: {
    official: 'Malaysia',
    flag: '🇲🇾',
    capital: 'Kuala Lumpur',
    region: 'South-Eastern Asia',
    languages: 'English, Malay',
    currency: 'Malaysian ringgit',
    currencySymbol: 'RM',
    population: '34M',
    area: '331K km²',
    landlocked: false,
    independent: true,
    gdp: '$400B',
    gdpPerCapita: '$11,386',
    military: '$4B',
    militaryPctGdp: '1.0%',
    lifeExpectancy: '76.7 yr',
    internetPct: '98%',
  },
  Mali: {
    official: 'Republic of Mali',
    flag: '🇲🇱',
    capital: 'Bamako',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '22M',
    area: '1.2M km²',
    landlocked: true,
    independent: true,
    gdp: '$25B',
    gdpPerCapita: '$1,044',
    military: '$785M',
    militaryPctGdp: '3.8%',
    lifeExpectancy: '60.4 yr',
    internetPct: '35%',
  },
  Mauritania: {
    official: 'Islamic Republic of Mauritania',
    flag: '🇲🇷',
    capital: 'Nouakchott',
    region: 'Western Africa',
    languages: 'Arabic',
    currency: 'Mauritanian ouguiya',
    currencySymbol: 'UM',
    population: '5M',
    area: '1.0M km²',
    landlocked: false,
    independent: true,
    gdp: '$11B',
    gdpPerCapita: '$2,136',
    military: '$277M',
    militaryPctGdp: '2.3%',
    lifeExpectancy: '68.5 yr',
    internetPct: '37%',
  },
  Mexico: {
    official: 'United Mexican States',
    flag: '🇲🇽',
    capital: 'Mexico City',
    region: 'North America',
    languages: 'Spanish',
    currency: 'Mexican peso',
    currencySymbol: '$',
    population: '131M',
    area: '2.0M km²',
    landlocked: false,
    independent: true,
    gdp: '$1.8T',
    gdpPerCapita: '$13,861',
    military: '$12B',
    militaryPctGdp: '0.7%',
    lifeExpectancy: '75.1 yr',
    internetPct: '81%',
  },
  Moldova: {
    official: 'Republic of Moldova',
    flag: '🇲🇩',
    capital: 'Chișinău',
    region: 'Eastern Europe',
    languages: 'Romanian',
    currency: 'Moldovan leu',
    currencySymbol: 'L',
    population: '3M',
    area: '34K km²',
    landlocked: true,
    independent: true,
    gdp: '$17B',
    gdpPerCapita: '$6,800',
    military: '$94M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '71.2 yr',
    internetPct: '80%',
  },
  Mongolia: {
    official: 'Mongolia',
    flag: '🇲🇳',
    capital: 'Ulan Bator',
    region: 'Eastern Asia',
    languages: 'Mongolian',
    currency: 'Mongolian tögrög',
    currencySymbol: '₮',
    population: '4M',
    area: '1.6M km²',
    landlocked: true,
    independent: true,
    gdp: '$20B',
    gdpPerCapita: '$5,839',
    military: '$111M',
    militaryPctGdp: '0.5%',
    lifeExpectancy: '72.1 yr',
    internetPct: '83%',
  },
  Montenegro: {
    official: 'Montenegro',
    flag: '🇲🇪',
    capital: 'Podgorica',
    region: 'Southeast Europe',
    languages: 'Montenegrin',
    currency: 'euro',
    currencySymbol: '€',
    population: '623K',
    area: '14K km²',
    landlocked: false,
    independent: true,
    gdp: '$8B',
    gdpPerCapita: '$12,260',
    military: '$114M',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '77.6 yr',
    internetPct: '90%',
  },
  Morocco: {
    official: 'Kingdom of Morocco',
    flag: '🇲🇦',
    capital: 'Rabat',
    region: 'Northern Africa',
    languages: 'Arabic, Berber',
    currency: 'Moroccan dirham',
    currencySymbol: 'د.م.',
    population: '37M',
    area: '447K km²',
    landlocked: false,
    independent: true,
    gdp: '$146B',
    gdpPerCapita: '$3,814',
    military: '$5B',
    militaryPctGdp: '3.6%',
    lifeExpectancy: '75.3 yr',
    internetPct: '91%',
  },
  Mozambique: {
    official: 'Republic of Mozambique',
    flag: '🇲🇿',
    capital: 'Maputo',
    region: 'Eastern Africa',
    languages: 'Portuguese',
    currency: 'Mozambican metical',
    currencySymbol: 'MT',
    population: '34M',
    area: '802K km²',
    landlocked: false,
    independent: true,
    gdp: '$21B',
    gdpPerCapita: '$622',
    military: '$404M',
    militaryPctGdp: '1.9%',
    lifeExpectancy: '63.6 yr',
    internetPct: '20%',
  },
  Myanmar: {
    official: 'Republic of the Union of Myanmar',
    flag: '🇲🇲',
    capital: 'Naypyidaw',
    region: 'South-Eastern Asia',
    languages: 'Burmese',
    currency: 'Burmese kyat',
    currencySymbol: 'Ks',
    population: '51M',
    area: '677K km²',
    landlocked: false,
    independent: true,
    gdp: '$67B',
    gdpPerCapita: '$1,233',
    military: '$2B',
    militaryPctGdp: '3.8%',
    lifeExpectancy: '66.9 yr',
    internetPct: '59%',
  },
  'N. Cyprus': {
    official: 'Republic of Cyprus',
    flag: '🇨🇾',
    capital: 'Nicosia',
    region: 'Southern Europe',
    languages: 'Greek, Turkish',
    currency: 'euro',
    currencySymbol: '€',
    population: '1M',
    area: '9K km²',
    landlocked: false,
    independent: true,
    gdp: '$35B',
    gdpPerCapita: '$36,624',
    military: '$559M',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '81.6 yr',
    internetPct: '91%',
  },
  Namibia: {
    official: 'Republic of Namibia',
    flag: '🇳🇦',
    capital: 'Windhoek',
    region: 'Southern Africa',
    languages: 'Afrikaans, German, English',
    currency: 'Namibian dollar',
    currencySymbol: '$',
    population: '3M',
    area: '826K km²',
    landlocked: false,
    independent: true,
    gdp: '$12B',
    gdpPerCapita: '$4,188',
    military: '$339M',
    militaryPctGdp: '2.7%',
    lifeExpectancy: '67.4 yr',
    internetPct: '64%',
  },
  Nepal: {
    official: 'Federal Democratic Republic of Nepal',
    flag: '🇳🇵',
    capital: 'Kathmandu',
    region: 'Southern Asia',
    languages: 'Nepali',
    currency: 'Nepalese rupee',
    currencySymbol: '₨',
    population: '30M',
    area: '147K km²',
    landlocked: true,
    independent: true,
    gdp: '$41B',
    gdpPerCapita: '$1,382',
    military: '$436M',
    militaryPctGdp: '1.1%',
    lifeExpectancy: '70.4 yr',
    internetPct: '56%',
  },
  Netherlands: {
    official: 'Kingdom of the Netherlands',
    flag: '🇳🇱',
    capital: 'Amsterdam',
    region: 'Western Europe',
    languages: 'Dutch',
    currency: 'euro',
    currencySymbol: '€',
    population: '18M',
    area: '42K km²',
    landlocked: false,
    independent: true,
    gdp: '$1.1T',
    gdpPerCapita: '$63,516',
    military: '$17B',
    militaryPctGdp: '1.4%',
    lifeExpectancy: '81.9 yr',
    internetPct: '97%',
  },
  'New Caledonia': {
    official: 'New Caledonia',
    flag: '🇳🇨',
    capital: 'Nouméa',
    region: 'Melanesia',
    languages: 'French',
    currency: 'CFP franc',
    currencySymbol: '₣',
    population: '265K',
    area: '19K km²',
    landlocked: false,
    independent: false,
    gdp: '$10B',
    gdpPerCapita: '$33,702',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '78.8 yr',
    internetPct: null,
  },
  'New Zealand': {
    official: 'New Zealand',
    flag: '🇳🇿',
    capital: 'Wellington',
    region: 'Australia and New Zealand',
    languages: 'English, Māori, New Zealand Sign Language',
    currency: 'New Zealand dollar',
    currencySymbol: '$',
    population: '5M',
    area: '269K km²',
    landlocked: false,
    independent: true,
    gdp: '$255B',
    gdpPerCapita: '$49,076',
    military: '$3B',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '83.0 yr',
    internetPct: '96%',
  },
  Nicaragua: {
    official: 'Republic of Nicaragua',
    flag: '🇳🇮',
    capital: 'Managua',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'Nicaraguan córdoba',
    currencySymbol: 'C$',
    population: '7M',
    area: '130K km²',
    landlocked: false,
    independent: true,
    gdp: '$18B',
    gdpPerCapita: '$2,609',
    military: '$99M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '74.9 yr',
    internetPct: '58%',
  },
  Niger: {
    official: 'Republic of Niger',
    flag: '🇳🇪',
    capital: 'Niamey',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '26M',
    area: '1.3M km²',
    landlocked: true,
    independent: true,
    gdp: '$17B',
    gdpPerCapita: '$638',
    military: '$332M',
    militaryPctGdp: '2.0%',
    lifeExpectancy: '61.2 yr',
    internetPct: '23%',
  },
  Nigeria: {
    official: 'Federal Republic of Nigeria',
    flag: '🇳🇬',
    capital: 'Abuja',
    region: 'Western Africa',
    languages: 'English',
    currency: 'Nigerian naira',
    currencySymbol: '₦',
    population: '224M',
    area: '924K km²',
    landlocked: false,
    independent: true,
    gdp: '$487B',
    gdpPerCapita: '$2,139',
    military: '$3B',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '54.5 yr',
    internetPct: '39%',
  },
  'North Korea': {
    official: 'Democratic People\'s Republic of Korea',
    flag: '🇰🇵',
    capital: 'Pyongyang',
    region: 'Eastern Asia',
    languages: 'Korean',
    currency: 'North Korean won',
    currencySymbol: '₩',
    population: '26M',
    area: '121K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '73.6 yr',
    internetPct: null,
  },
  Norway: {
    official: 'Kingdom of Norway',
    flag: '🇳🇴',
    capital: 'Oslo',
    region: 'Northern Europe',
    languages: 'Norwegian Nynorsk, Norwegian Bokmål, Sami',
    currency: 'Norwegian krone',
    currencySymbol: 'kr',
    population: '6M',
    area: '386K km²',
    landlocked: false,
    independent: true,
    gdp: '$483B',
    gdpPerCapita: '$87,497',
    military: '$9B',
    militaryPctGdp: '1.8%',
    lifeExpectancy: '83.1 yr',
    internetPct: '99%',
  },
  Oman: {
    official: 'Sultanate of Oman',
    flag: '🇴🇲',
    capital: 'Muscat',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Omani rial',
    currencySymbol: 'ر.ع.',
    population: '5M',
    area: '310K km²',
    landlocked: false,
    independent: true,
    gdp: '$106B',
    gdpPerCapita: '$21,028',
    military: '$6B',
    militaryPctGdp: '5.5%',
    lifeExpectancy: '80.0 yr',
    internetPct: '95%',
  },
  Pakistan: {
    official: 'Islamic Republic of Pakistan',
    flag: '🇵🇰',
    capital: 'Islamabad',
    region: 'Southern Asia',
    languages: 'English, Urdu',
    currency: 'Pakistani rupee',
    currencySymbol: '₨',
    population: '241M',
    area: '796K km²',
    landlocked: false,
    independent: true,
    gdp: '$337B',
    gdpPerCapita: '$1,360',
    military: '$9B',
    militaryPctGdp: '2.9%',
    lifeExpectancy: '67.6 yr',
    internetPct: '27%',
  },
  Palestine: {
    official: 'State of Palestine',
    flag: '🇵🇸',
    capital: 'Ramallah',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Egyptian pound',
    currencySymbol: 'E£',
    population: '5M',
    area: '6K km²',
    landlocked: false,
    independent: false,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Panama: {
    official: 'Republic of Panama',
    flag: '🇵🇦',
    capital: 'Panama City',
    region: 'Central America',
    languages: 'Spanish',
    currency: 'Panamanian balboa',
    currencySymbol: 'B/.',
    population: '4M',
    area: '75K km²',
    landlocked: false,
    independent: true,
    gdp: '$84B',
    gdpPerCapita: '$18,797',
    military: '$0',
    militaryPctGdp: null,
    lifeExpectancy: '79.6 yr',
    internetPct: '69%',
  },
  'Papua New Guinea': {
    official: 'Independent State of Papua New Guinea',
    flag: '🇵🇬',
    capital: 'Port Moresby',
    region: 'Melanesia',
    languages: 'English, Hiri Motu, Tok Pisin',
    currency: 'Papua New Guinean kina',
    currencySymbol: 'K',
    population: '12M',
    area: '463K km²',
    landlocked: false,
    independent: true,
    gdp: '$31B',
    gdpPerCapita: '$2,966',
    military: '$97M',
    militaryPctGdp: '0.3%',
    lifeExpectancy: '66.1 yr',
    internetPct: '24%',
  },
  Paraguay: {
    official: 'Republic of Paraguay',
    flag: '🇵🇾',
    capital: 'Asunción',
    region: 'South America',
    languages: 'Guaraní, Spanish',
    currency: 'Paraguayan guaraní',
    currencySymbol: '₲',
    population: '6M',
    area: '407K km²',
    landlocked: true,
    independent: true,
    gdp: '$43B',
    gdpPerCapita: '$6,300',
    military: '$398M',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '73.8 yr',
    internetPct: '78%',
  },
  Peru: {
    official: 'Republic of Peru',
    flag: '🇵🇪',
    capital: 'Lima',
    region: 'South America',
    languages: 'Aymara, Quechua, Spanish',
    currency: 'Peruvian sol',
    currencySymbol: 'S/ ',
    population: '34M',
    area: '1.3M km²',
    landlocked: false,
    independent: true,
    gdp: '$267B',
    gdpPerCapita: '$7,888',
    military: '$3B',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '77.7 yr',
    internetPct: '79%',
  },
  Philippines: {
    official: 'Republic of the Philippines',
    flag: '🇵🇭',
    capital: 'Manila',
    region: 'South-Eastern Asia',
    languages: 'English, Filipino',
    currency: 'Philippine peso',
    currencySymbol: '₱',
    population: '114M',
    area: '342K km²',
    landlocked: false,
    independent: true,
    gdp: '$437B',
    gdpPerCapita: '$3,804',
    military: '$5B',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '69.8 yr',
    internetPct: '84%',
  },
  Poland: {
    official: 'Republic of Poland',
    flag: '🇵🇱',
    capital: 'Warsaw',
    region: 'Central Europe',
    languages: 'Polish',
    currency: 'Polish złoty',
    currencySymbol: 'zł',
    population: '37M',
    area: '313K km²',
    landlocked: false,
    independent: true,
    gdp: '$812B',
    gdpPerCapita: '$22,145',
    military: '$26B',
    militaryPctGdp: '3.3%',
    lifeExpectancy: '78.5 yr',
    internetPct: '86%',
  },
  Portugal: {
    official: 'Portuguese Republic',
    flag: '🇵🇹',
    capital: 'Lisbon',
    region: 'Southern Europe',
    languages: 'Portuguese',
    currency: 'euro',
    currencySymbol: '€',
    population: '11M',
    area: '92K km²',
    landlocked: false,
    independent: true,
    gdp: '$292B',
    gdpPerCapita: '$27,635',
    military: '$4B',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '82.3 yr',
    internetPct: '86%',
  },
  'Puerto Rico': {
    official: 'Commonwealth of Puerto Rico',
    flag: '🇵🇷',
    capital: 'San Juan',
    region: 'Caribbean',
    languages: 'English, Spanish',
    currency: 'United States dollar',
    currencySymbol: '$',
    population: '3M',
    area: '9K km²',
    landlocked: false,
    independent: false,
    gdp: '$118B',
    gdpPerCapita: '$36,981',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '81.7 yr',
    internetPct: '87%',
  },
  Qatar: {
    official: 'State of Qatar',
    flag: '🇶🇦',
    capital: 'Doha',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Qatari riyal',
    currencySymbol: 'ر.ق',
    population: '3M',
    area: '12K km²',
    landlocked: false,
    independent: true,
    gdp: '$217B',
    gdpPerCapita: '$81,817',
    military: '$15B',
    militaryPctGdp: '6.5%',
    lifeExpectancy: '82.4 yr',
    internetPct: '100%',
  },
  Romania: {
    official: 'Romania',
    flag: '🇷🇴',
    capital: 'Bucharest',
    region: 'Southeast Europe',
    languages: 'Romanian',
    currency: 'Romanian leu',
    currencySymbol: 'lei',
    population: '19M',
    area: '238K km²',
    landlocked: false,
    independent: true,
    gdp: '$348B',
    gdpPerCapita: '$18,244',
    military: '$6B',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '76.6 yr',
    internetPct: '89%',
  },
  Russia: {
    official: 'Russian Federation',
    flag: '🇷🇺',
    capital: 'Moscow',
    region: 'Eastern Europe',
    languages: 'Russian',
    currency: 'Russian ruble',
    currencySymbol: '₽',
    population: '146M',
    area: '17.1M km²',
    landlocked: false,
    independent: true,
    gdp: '$2.1T',
    gdpPerCapita: '$14,159',
    military: '$109B',
    militaryPctGdp: '5.4%',
    lifeExpectancy: '73.3 yr',
    internetPct: '92%',
  },
  Rwanda: {
    official: 'Republic of Rwanda',
    flag: '🇷🇼',
    capital: 'Kigali',
    region: 'Eastern Africa',
    languages: 'English, French, Kinyarwanda',
    currency: 'Rwandan franc',
    currencySymbol: 'Fr',
    population: '14M',
    area: '26K km²',
    landlocked: true,
    independent: true,
    gdp: '$14B',
    gdpPerCapita: '$1,027',
    military: '$179M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '67.8 yr',
    internetPct: '34%',
  },
  'S. Sudan': {
    official: 'Republic of South Sudan',
    flag: '🇸🇸',
    capital: 'Juba',
    region: 'Middle Africa',
    languages: 'English',
    currency: 'South Sudanese pound',
    currencySymbol: '£',
    population: '16M',
    area: '620K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: '$1B',
    militaryPctGdp: '2.1%',
    lifeExpectancy: '57.6 yr',
    internetPct: '9%',
  },
  'Saudi Arabia': {
    official: 'Kingdom of Saudi Arabia',
    flag: '🇸🇦',
    capital: 'Riyadh',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Saudi riyal',
    currencySymbol: 'ر.س',
    population: '35M',
    area: '2.1M km²',
    landlocked: false,
    independent: true,
    gdp: '$1.2T',
    gdpPerCapita: '$36,157',
    military: '$78B',
    militaryPctGdp: '7.3%',
    lifeExpectancy: '78.7 yr',
    internetPct: '100%',
  },
  Senegal: {
    official: 'Republic of Senegal',
    flag: '🇸🇳',
    capital: 'Dakar',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '19M',
    area: '197K km²',
    landlocked: false,
    independent: true,
    gdp: '$31B',
    gdpPerCapita: '$1,698',
    military: '$449M',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '68.7 yr',
    internetPct: '61%',
  },
  Serbia: {
    official: 'Republic of Serbia',
    flag: '🇷🇸',
    capital: 'Belgrade',
    region: 'Southeast Europe',
    languages: 'Serbian',
    currency: 'Serbian dinar',
    currencySymbol: 'дин.',
    population: '7M',
    area: '78K km²',
    landlocked: true,
    independent: true,
    gdp: '$81B',
    gdpPerCapita: '$12,282',
    military: '$2B',
    militaryPctGdp: '2.2%',
    lifeExpectancy: '76.2 yr',
    internetPct: '85%',
  },
  'Sierra Leone': {
    official: 'Republic of Sierra Leone',
    flag: '🇸🇱',
    capital: 'Freetown',
    region: 'Western Africa',
    languages: 'English',
    currency: 'Leone',
    currencySymbol: 'Le',
    population: '9M',
    area: '72K km²',
    landlocked: false,
    independent: true,
    gdp: '$6B',
    gdpPerCapita: '$758',
    military: '$38M',
    militaryPctGdp: '0.6%',
    lifeExpectancy: '61.8 yr',
    internetPct: '21%',
  },
  Slovakia: {
    official: 'Slovak Republic',
    flag: '🇸🇰',
    capital: 'Bratislava',
    region: 'Central Europe',
    languages: 'Slovak',
    currency: 'euro',
    currencySymbol: '€',
    population: '5M',
    area: '49K km²',
    landlocked: true,
    independent: true,
    gdp: '$134B',
    gdpPerCapita: '$24,615',
    military: '$2B',
    militaryPctGdp: '1.8%',
    lifeExpectancy: '78.0 yr',
    internetPct: '87%',
  },
  Slovenia: {
    official: 'Republic of Slovenia',
    flag: '🇸🇮',
    capital: 'Ljubljana',
    region: 'Central Europe',
    languages: 'Slovene',
    currency: 'euro',
    currencySymbol: '€',
    population: '2M',
    area: '20K km²',
    landlocked: false,
    independent: true,
    gdp: '$69B',
    gdpPerCapita: '$32,660',
    military: '$913M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '82.0 yr',
    internetPct: '90%',
  },
  'Solomon Is.': {
    official: 'Solomon Islands',
    flag: '🇸🇧',
    capital: 'Honiara',
    region: 'Melanesia',
    languages: 'English',
    currency: 'Solomon Islands dollar',
    currencySymbol: '$',
    population: '750K',
    area: '29K km²',
    landlocked: false,
    independent: true,
    gdp: '$2B',
    gdpPerCapita: '$1,883',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '70.5 yr',
    internetPct: '42%',
  },
  Somalia: {
    official: 'Federal Republic of Somalia',
    flag: '🇸🇴',
    capital: 'Mogadishu',
    region: 'Eastern Africa',
    languages: 'Arabic, Somali',
    currency: 'Somali shilling',
    currencySymbol: 'Sh',
    population: '20M',
    area: '638K km²',
    landlocked: false,
    independent: true,
    gdp: '$11B',
    gdpPerCapita: '$597',
    military: '$141M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '58.8 yr',
    internetPct: '28%',
  },
  Somaliland: {
    official: 'Federal Republic of Somalia',
    flag: '🇸🇴',
    capital: 'Mogadishu',
    region: 'Eastern Africa',
    languages: 'Arabic, Somali',
    currency: 'Somali shilling',
    currencySymbol: 'Sh',
    population: '20M',
    area: '638K km²',
    landlocked: false,
    independent: true,
    gdp: '$11B',
    gdpPerCapita: '$597',
    military: '$141M',
    militaryPctGdp: '1.3%',
    lifeExpectancy: '58.8 yr',
    internetPct: '28%',
  },
  'South Africa': {
    official: 'Republic of South Africa',
    flag: '🇿🇦',
    capital: 'Pretoria',
    region: 'Southern Africa',
    languages: 'Afrikaans, English, Southern Ndebele',
    currency: 'South African rand',
    currencySymbol: 'R',
    population: '63M',
    area: '1.2M km²',
    landlocked: false,
    independent: true,
    gdp: '$381B',
    gdpPerCapita: '$6,034',
    military: '$3B',
    militaryPctGdp: '0.8%',
    lifeExpectancy: '66.1 yr',
    internetPct: '76%',
  },
  'South Korea': {
    official: 'Republic of Korea',
    flag: '🇰🇷',
    capital: 'Seoul',
    region: 'Eastern Asia',
    languages: 'Korean',
    currency: 'South Korean won',
    currencySymbol: '₩',
    population: '51M',
    area: '100K km²',
    landlocked: false,
    independent: true,
    gdp: '$1.8T',
    gdpPerCapita: '$35,674',
    military: '$48B',
    militaryPctGdp: '2.6%',
    lifeExpectancy: '83.4 yr',
    internetPct: '97%',
  },
  Spain: {
    official: 'Kingdom of Spain',
    flag: '🇪🇸',
    capital: 'Madrid',
    region: 'Southern Europe',
    languages: 'Spanish, Catalan, Basque',
    currency: 'euro',
    currencySymbol: '€',
    population: '49M',
    area: '506K km²',
    landlocked: false,
    independent: true,
    gdp: '$1.6T',
    gdpPerCapita: '$33,493',
    military: '$24B',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '83.9 yr',
    internetPct: '95%',
  },
  'Sri Lanka': {
    official: 'Democratic Socialist Republic of Sri Lanka',
    flag: '🇱🇰',
    capital: 'Sri Jayawardenepura Kotte',
    region: 'Southern Asia',
    languages: 'Sinhala, Tamil',
    currency: 'Sri Lankan rupee',
    currencySymbol: 'Rs  රු',
    population: '22M',
    area: '66K km²',
    landlocked: false,
    independent: true,
    gdp: '$84B',
    gdpPerCapita: '$3,799',
    military: '$1B',
    militaryPctGdp: '1.6%',
    lifeExpectancy: '77.5 yr',
    internetPct: '51%',
  },
  Sudan: {
    official: 'Republic of the Sudan',
    flag: '🇸🇩',
    capital: 'Khartoum',
    region: 'Northern Africa',
    languages: 'Arabic, English',
    currency: 'Sudanese pound',
    currencySymbol: 'ج.س',
    population: '52M',
    area: '1.9M km²',
    landlocked: false,
    independent: true,
    gdp: '$40B',
    gdpPerCapita: '$797',
    military: '$375M',
    militaryPctGdp: '0.9%',
    lifeExpectancy: '66.3 yr',
    internetPct: '26%',
  },
  Suriname: {
    official: 'Republic of Suriname',
    flag: '🇸🇷',
    capital: 'Paramaribo',
    region: 'South America',
    languages: 'Dutch',
    currency: 'Surinamese dollar',
    currencySymbol: '$',
    population: '616K',
    area: '164K km²',
    landlocked: false,
    independent: true,
    gdp: '$3B',
    gdpPerCapita: '$5,522',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '73.6 yr',
    internetPct: '78%',
  },
  Sweden: {
    official: 'Kingdom of Sweden',
    flag: '🇸🇪',
    capital: 'Stockholm',
    region: 'Northern Europe',
    languages: 'Swedish',
    currency: 'Swedish krona',
    currencySymbol: 'kr',
    population: '11M',
    area: '450K km²',
    landlocked: false,
    independent: true,
    gdp: '$579B',
    gdpPerCapita: '$54,950',
    military: '$9B',
    militaryPctGdp: '1.5%',
    lifeExpectancy: '83.3 yr',
    internetPct: '96%',
  },
  Switzerland: {
    official: 'Swiss Confederation',
    flag: '🇨🇭',
    capital: 'Bern',
    region: 'Western Europe',
    languages: 'French, Swiss German, Italian',
    currency: 'Swiss franc',
    currencySymbol: 'Fr.',
    population: '9M',
    area: '41K km²',
    landlocked: true,
    independent: true,
    gdp: '$894B',
    gdpPerCapita: '$100,624',
    military: '$6B',
    militaryPctGdp: '0.7%',
    lifeExpectancy: '84.1 yr',
    internetPct: '97%',
  },
  Syria: {
    official: 'Syrian Arab Republic',
    flag: '🇸🇾',
    capital: 'Damascus',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Syrian pound',
    currencySymbol: '£',
    population: '26M',
    area: '185K km²',
    landlocked: false,
    independent: true,
    gdp: '$24B',
    gdpPerCapita: '$1,052',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '72.1 yr',
    internetPct: null,
  },
  Taiwan: {
    official: 'Republic of China (Taiwan)',
    flag: '🇹🇼',
    capital: 'Taipei',
    region: 'Eastern Asia',
    languages: 'Chinese',
    currency: 'New Taiwan dollar',
    currencySymbol: '$',
    population: '23M',
    area: '36K km²',
    landlocked: false,
    independent: false,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Tajikistan: {
    official: 'Republic of Tajikistan',
    flag: '🇹🇯',
    capital: 'Dushanbe',
    region: 'Central Asia',
    languages: 'Russian, Tajik',
    currency: 'Tajikistani somoni',
    currencySymbol: 'ЅМ',
    population: '10M',
    area: '143K km²',
    landlocked: true,
    independent: true,
    gdp: '$12B',
    gdpPerCapita: '$1,178',
    military: '$285M',
    militaryPctGdp: '2.4%',
    lifeExpectancy: '71.8 yr',
    internetPct: '57%',
  },
  Tanzania: {
    official: 'United Republic of Tanzania',
    flag: '🇹🇿',
    capital: 'Dodoma',
    region: 'Eastern Africa',
    languages: 'English, Swahili',
    currency: 'Tanzanian shilling',
    currencySymbol: 'Sh',
    population: '68M',
    area: '947K km²',
    landlocked: false,
    independent: true,
    gdp: '$79B',
    gdpPerCapita: '$1,224',
    military: '$946M',
    militaryPctGdp: '1.2%',
    lifeExpectancy: '67.0 yr',
    internetPct: '29%',
  },
  Thailand: {
    official: 'Kingdom of Thailand',
    flag: '🇹🇭',
    capital: 'Bangkok',
    region: 'South-Eastern Asia',
    languages: 'Thai',
    currency: 'Thai baht',
    currencySymbol: '฿',
    population: '66M',
    area: '513K km²',
    landlocked: false,
    independent: true,
    gdp: '$516B',
    gdpPerCapita: '$7,195',
    military: '$6B',
    militaryPctGdp: '1.1%',
    lifeExpectancy: '76.4 yr',
    internetPct: '90%',
  },
  'Timor-Leste': {
    official: 'Democratic Republic of Timor-Leste',
    flag: '🇹🇱',
    capital: 'Dili',
    region: 'South-Eastern Asia',
    languages: 'Portuguese, Tetum',
    currency: 'United States dollar',
    currencySymbol: '$',
    population: '1M',
    area: '15K km²',
    landlocked: false,
    independent: true,
    gdp: '$2B',
    gdpPerCapita: '$1,502',
    military: '$55M',
    militaryPctGdp: '2.6%',
    lifeExpectancy: '67.7 yr',
    internetPct: '34%',
  },
  Togo: {
    official: 'Togolese Republic',
    flag: '🇹🇬',
    capital: 'Lomé',
    region: 'Western Africa',
    languages: 'French',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    population: '8M',
    area: '57K km²',
    landlocked: false,
    independent: true,
    gdp: '$10B',
    gdpPerCapita: '$1,055',
    military: '$276M',
    militaryPctGdp: '3.0%',
    lifeExpectancy: '62.7 yr',
    internetPct: '37%',
  },
  'Trinidad and Tobago': {
    official: 'Republic of Trinidad and Tobago',
    flag: '🇹🇹',
    capital: 'Port of Spain',
    region: 'Caribbean',
    languages: 'English',
    currency: 'Trinidad and Tobago dollar',
    currencySymbol: '$',
    population: '1M',
    area: '5K km²',
    landlocked: false,
    independent: true,
    gdp: '$25B',
    gdpPerCapita: '$18,308',
    military: '$243M',
    militaryPctGdp: '1.0%',
    lifeExpectancy: '73.5 yr',
    internetPct: '85%',
  },
  Tunisia: {
    official: 'Tunisian Republic',
    flag: '🇹🇳',
    capital: 'Tunis',
    region: 'Northern Africa',
    languages: 'Arabic',
    currency: 'Tunisian dinar',
    currencySymbol: 'د.ت',
    population: '12M',
    area: '164K km²',
    landlocked: false,
    independent: true,
    gdp: '$48B',
    gdpPerCapita: '$3,951',
    military: '$1B',
    militaryPctGdp: '2.5%',
    lifeExpectancy: '76.5 yr',
    internetPct: '72%',
  },
  Turkey: {
    official: 'Republic of Turkey',
    flag: '🇹🇷',
    capital: 'Ankara',
    region: 'Western Asia',
    languages: 'Turkish',
    currency: 'Turkish lira',
    currencySymbol: '₺',
    population: '86M',
    area: '784K km²',
    landlocked: false,
    independent: true,
    gdp: '$1.1T',
    gdpPerCapita: '$13,375',
    military: '$20B',
    militaryPctGdp: '1.7%',
    lifeExpectancy: '77.2 yr',
    internetPct: '86%',
  },
  Turkmenistan: {
    official: 'Turkmenistan',
    flag: '🇹🇲',
    capital: 'Ashgabat',
    region: 'Central Asia',
    languages: 'Russian, Turkmen',
    currency: 'Turkmenistan manat',
    currencySymbol: 'm',
    population: '7M',
    area: '488K km²',
    landlocked: true,
    independent: true,
    gdp: '$46B',
    gdpPerCapita: '$6,232',
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: '70.1 yr',
    internetPct: null,
  },
  Uganda: {
    official: 'Republic of Uganda',
    flag: '🇺🇬',
    capital: 'Kampala',
    region: 'Eastern Africa',
    languages: 'English, Swahili',
    currency: 'Ugandan shilling',
    currencySymbol: 'Sh',
    population: '46M',
    area: '242K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Ukraine: {
    official: 'Ukraine',
    flag: '🇺🇦',
    capital: 'Kyiv',
    region: 'Eastern Europe',
    languages: 'Ukrainian',
    currency: 'Ukrainian hryvnia',
    currencySymbol: '₴',
    population: '33M',
    area: '604K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  'United Arab Emirates': {
    official: 'United Arab Emirates',
    flag: '🇦🇪',
    capital: 'Abu Dhabi',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'United Arab Emirates dirham',
    currencySymbol: 'د.إ',
    population: '11M',
    area: '84K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  'United Kingdom': {
    official: 'United Kingdom of Great Britain and Northern Ireland',
    flag: '🇬🇧',
    capital: 'London',
    region: 'Northern Europe',
    languages: 'English',
    currency: 'British pound',
    currencySymbol: '£',
    population: '69M',
    area: '244K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  'United States of America': {
    official: 'United States of America',
    flag: '🇺🇸',
    capital: 'Washington, D.C.',
    region: 'North America',
    languages: 'English',
    currency: 'United States dollar',
    currencySymbol: '$',
    population: '340M',
    area: '9.5M km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Uruguay: {
    official: 'Oriental Republic of Uruguay',
    flag: '🇺🇾',
    capital: 'Montevideo',
    region: 'South America',
    languages: 'Spanish',
    currency: 'Uruguayan peso',
    currencySymbol: '$',
    population: '3M',
    area: '181K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Uzbekistan: {
    official: 'Republic of Uzbekistan',
    flag: '🇺🇿',
    capital: 'Tashkent',
    region: 'Central Asia',
    languages: 'Russian, Uzbek',
    currency: 'Uzbekistani soʻm',
    currencySymbol: 'so\'m',
    population: '38M',
    area: '447K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Vanuatu: {
    official: 'Republic of Vanuatu',
    flag: '🇻🇺',
    capital: 'Port Vila',
    region: 'Melanesia',
    languages: 'Bislama, English, French',
    currency: 'Vanuatu vatu',
    currencySymbol: 'Vt',
    population: '321K',
    area: '12K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Venezuela: {
    official: 'Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
    capital: 'Caracas',
    region: 'South America',
    languages: 'Spanish',
    currency: 'Venezuelan bolívar soberano',
    currencySymbol: 'Bs.S.',
    population: '29M',
    area: '916K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Vietnam: {
    official: 'Socialist Republic of Vietnam',
    flag: '🇻🇳',
    capital: 'Hanoi',
    region: 'South-Eastern Asia',
    languages: 'Vietnamese',
    currency: 'Vietnamese đồng',
    currencySymbol: '₫',
    population: '101M',
    area: '331K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  'W. Sahara': {
    official: 'Sahrawi Arab Democratic Republic',
    flag: '🇪🇭',
    capital: 'El Aaiún',
    region: 'Northern Africa',
    languages: 'Berber, Hassaniya, Spanish',
    currency: 'Algerian dinar',
    currencySymbol: 'دج',
    population: '601K',
    area: '266K km²',
    landlocked: false,
    independent: false,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Yemen: {
    official: 'Republic of Yemen',
    flag: '🇾🇪',
    capital: 'Sana\'a',
    region: 'Western Asia',
    languages: 'Arabic',
    currency: 'Yemeni rial',
    currencySymbol: '﷼',
    population: '33M',
    area: '528K km²',
    landlocked: false,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Zambia: {
    official: 'Republic of Zambia',
    flag: '🇿🇲',
    capital: 'Lusaka',
    region: 'Eastern Africa',
    languages: 'English',
    currency: 'Zambian kwacha',
    currencySymbol: 'ZK',
    population: '20M',
    area: '753K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  Zimbabwe: {
    official: 'Republic of Zimbabwe',
    flag: '🇿🇼',
    capital: 'Harare',
    region: 'Southern Africa',
    languages: 'Chibarwe, English, Kalanga',
    currency: 'Zimbabwean dollar',
    currencySymbol: '$',
    population: '17M',
    area: '391K km²',
    landlocked: true,
    independent: true,
    gdp: null,
    gdpPerCapita: null,
    military: null,
    militaryPctGdp: null,
    lifeExpectancy: null,
    internetPct: null,
  },
  eSwatini: {
    official: 'Kingdom of Eswatini',
    flag: '🇸🇿',
    capital: 'Mbabane',
    region: 'Southern Africa',
    languages: 'English, Swazi',
    currency: 'Swazi lilangeni',
    currencySymbol: 'L',
    population: '1M',
    area: '17K km²',
    landlocked: true,
    independent: true,
    gdp: '$5B',
    gdpPerCapita: '$3,756',
    military: '$71M',
    militaryPctGdp: '1.4%',
    lifeExpectancy: '64.1 yr',
    internetPct: '58%',
  },
};
