import { geoBounds, geoContains } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import type { GeometryCollection, Topology } from 'topojson-specification';
import { type CapCuller, createCapCuller } from './cap-cull';
import { decodeGeographyArc } from './geography-codec';

export type GeographyTier = 'motion' | 'overview' | 'regional' | 'detail';
type CountryTopology = Topology<{ countries: GeometryCollection; land: GeometryCollection }>;

/** At rest, keep source simplification below half a logical pixel (up to scale 8000).
 * Motion uses a light shared-arc tier; the final frame always restores detail. */
export function geographyTier(scale: number, moving = false): GeographyTier {
  if (moving) return 'motion';
  if (scale <= 500) return 'overview';
  if (scale <= 2000) return 'regional';
  return 'detail';
}

export interface GlobeGeography {
  land: CapCuller;
  borders: CapCuller;
  ice: CapCuller;
  country: (name: string) => CapCuller | undefined;
  countryNamed: (name: string) => GeoJSON.Feature | undefined;
  countryAt: (lng: number, lat: number) => GeoJSON.Feature | undefined;
}

const cache = new Map<GeographyTier, GlobeGeography>();

/** Each tier is decoded once, only if the camera needs it. All four layers
 * use one topology; mixing a detailed coast with a coarse highlight leaves
 * visible wedges at the shore. Generated by scripts/generate-globe-geography.mjs. */
export function getGlobeGeography(tier: GeographyTier): GlobeGeography {
  const cached = cache.get(tier);
  if (cached) return cached;
  const packed = (
    tier === 'motion'
      ? require('../../assets/geo/countries-motion.json')
      : tier === 'overview'
        ? require('../../assets/geo/countries-overview.json')
        : tier === 'regional'
          ? require('../../assets/geo/countries-regional.json')
          : require('../../assets/geo/countries-detail.json')
  ) as Omit<CountryTopology, 'arcs'> & { arcs: string[] };
  const topology = { ...packed, arcs: packed.arcs.map(decodeGeographyArc) };
  const countries = feature(topology, topology.objects.countries) as GeoJSON.FeatureCollection;
  const byName = new Map(countries.features.map((f) => [f.properties?.name as string, f]));
  const bounds = countries.features.map((country) => geoBounds(country));
  const countryCullers = new Map<string, CapCuller>();
  const result: GlobeGeography = {
    land: createCapCuller(feature(topology, topology.objects.land)),
    borders: createCapCuller(mesh(topology, topology.objects.countries, (a, b) => a !== b)),
    ice: createCapCuller({
      type: 'FeatureCollection',
      features: countries.features.filter((f) =>
        ['Antarctica', 'Greenland'].includes(f.properties?.name as string),
      ),
    }),
    countryNamed: (name) => byName.get(name),
    countryAt(lng, lat) {
      return countries.features.find((country, i) => {
        const bbox = bounds[i];
        if (!bbox) return false;
        const [[west, south], [east, north]] = bbox;
        const withinLng = west <= east ? lng >= west && lng <= east : lng >= west || lng <= east;
        return withinLng && lat >= south && lat <= north && geoContains(country, [lng, lat]);
      });
    },
    country(name) {
      const cachedCountry = countryCullers.get(name);
      if (cachedCountry) return cachedCountry;
      const country = byName.get(name);
      if (!country) return undefined;
      const culler = createCapCuller(country);
      countryCullers.set(name, culler);
      return culler;
    },
  };
  cache.set(tier, result);
  return result;
}
