/**
 * ISO 3166-1 alpha-2 → topojson `properties.name` lookup.
 *
 * Our world map feature set (`data/countries-110m.json`, Natural Earth 1:110m)
 * keys features by `properties.name`, not by ISO code. This table bridges the
 * two so blocks that carry `codes: string[]` (ISO-2) can be mapped to the
 * renderable feature.
 *
 * Covers ~130 codes that appear in the zuhd source list. Unknown codes return
 * undefined and the caller should fall back (e.g. skip highlighting, show the
 * raw code as text).
 */

export const CC_TO_TOPOJSON_NAME: Record<string, string> = {
  AD: 'Andorra',
  AE: 'United Arab Emirates',
  AF: 'Afghanistan',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AR: 'Argentina',
  AT: 'Austria',
  AU: 'Australia',
  AZ: 'Azerbaijan',
  BA: 'Bosnia and Herz.',
  BD: 'Bangladesh',
  BE: 'Belgium',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrain',
  BI: 'Burundi',
  BJ: 'Benin',
  BN: 'Brunei',
  BO: 'Bolivia',
  BR: 'Brazil',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BW: 'Botswana',
  BY: 'Belarus',
  BZ: 'Belize',
  CA: 'Canada',
  CD: 'Dem. Rep. Congo',
  CF: 'Central African Rep.',
  CG: 'Congo',
  CH: 'Switzerland',
  CI: "Côte d'Ivoire",
  CL: 'Chile',
  CM: 'Cameroon',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czechia',
  DE: 'Germany',
  DJ: 'Djibouti',
  DK: 'Denmark',
  DO: 'Dominican Rep.',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egypt',
  EH: 'W. Sahara',
  ER: 'Eritrea',
  ES: 'Spain',
  ET: 'Ethiopia',
  FI: 'Finland',
  FJ: 'Fiji',
  FR: 'France',
  GA: 'Gabon',
  GB: 'United Kingdom',
  GE: 'Georgia',
  GH: 'Ghana',
  GL: 'Greenland',
  GM: 'Gambia',
  GN: 'Guinea',
  GQ: 'Eq. Guinea',
  GR: 'Greece',
  GT: 'Guatemala',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HN: 'Honduras',
  HR: 'Croatia',
  HT: 'Haiti',
  HU: 'Hungary',
  ID: 'Indonesia',
  IE: 'Ireland',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',
  IR: 'Iran',
  IS: 'Iceland',
  IT: 'Italy',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  KE: 'Kenya',
  KG: 'Kyrgyzstan',
  KH: 'Cambodia',
  KP: 'North Korea',
  KR: 'South Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan',
  LA: 'Laos',
  LB: 'Lebanon',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  LY: 'Libya',
  MA: 'Morocco',
  MD: 'Moldova',
  ME: 'Montenegro',
  MG: 'Madagascar',
  // Natural Earth 1:110m still calls this feature `Macedonia`, and this table
  // is a *join key* onto that string, not a label. Keying it by the country's
  // current name meant the lookup missed entirely: the feature got no `iso2`,
  // so the map could never shade it on any metric and clicking it could not
  // open its profile — the country was on the map and unreachable. What the
  // reader sees is `place-names.ts`'s job, and that already renames it.
  MK: 'Macedonia',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MR: 'Mauritania',
  MW: 'Malawi',
  MX: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'New Caledonia',
  NE: 'Niger',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands',
  NO: 'Norway',
  NP: 'Nepal',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Poland',
  PR: 'Puerto Rico',
  PS: 'Palestine',
  PT: 'Portugal',
  PY: 'Paraguay',
  QA: 'Qatar',
  RO: 'Romania',
  RS: 'Serbia',
  RU: 'Russia',
  RW: 'Rwanda',
  SA: 'Saudi Arabia',
  SB: 'Solomon Is.',
  SD: 'Sudan',
  SE: 'Sweden',
  SI: 'Slovenia',
  SK: 'Slovakia',
  SL: 'Sierra Leone',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'S. Sudan',
  SV: 'El Salvador',
  SY: 'Syria',
  SZ: 'eSwatini',
  TD: 'Chad',
  TG: 'Togo',
  TH: 'Thailand',
  TJ: 'Tajikistan',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunisia',
  TR: 'Turkey',
  TT: 'Trinidad and Tobago',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  UA: 'Ukraine',
  UG: 'Uganda',
  US: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  // Was simply absent, with the same consequence as the Macedonia mismatch:
  // unshadeable on every metric, and not clickable through to its profile.
  VU: 'Vanuatu',
  XK: 'Kosovo',
  YE: 'Yemen',
  ZA: 'South Africa',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export function topojsonNameFromCode(cc: string): string | undefined {
  return CC_TO_TOPOJSON_NAME[cc.toUpperCase()];
}

const TOPOJSON_NAME_TO_CC: Record<string, string> = Object.fromEntries(
  Object.entries(CC_TO_TOPOJSON_NAME).map(([cc, name]) => [name, cc]),
);

export function codeFromTopojsonName(name: string): string | undefined {
  return TOPOJSON_NAME_TO_CC[name];
}

/** Human-facing name (often matches topojson name, but some differ). For the
 *  zuhd feed we just reuse the topojson names — they read naturally enough.
 *  If we later want fully-proper names ("United States" vs "United States of
 *  America") we can split this. */
export function displayNameFromCode(cc: string): string {
  return CC_TO_TOPOJSON_NAME[cc.toUpperCase()] ?? cc.toUpperCase();
}
