import type { ConflictEvent, ConflictSnapshot } from '@shared/types';
import { useMemo } from 'react';
import fixture from '../lib/conflict-fixture.json';
import { isConflictSnapshot } from '../lib/validate';

const EMPTY_EVENTS: ConflictEvent[] = [];

// Validate the bundled fixture once at module init so a malformed file
// degrades gracefully (empty layer) rather than crashing the app. Using
// the same validator the network path will use means the validator is
// already test-exercised today.
const VALIDATED: ConflictSnapshot | null = isConflictSnapshot(fixture) ? fixture : null;

/** PROTOTYPE: reads a bundled, hand-fetched UCDP snapshot from
 *  lib/conflict-fixture.json. The fixture is generated by
 *  scripts/fetch-conflict-prototype.js; see that file's header for the
 *  upstream + filtering decisions.
 *
 *  ─── Backend handoff ──────────────────────────────────────────────────
 *  When the snapshot moves server-side, replace the body of this hook with:
 *
 *    const snapshot = useFetchJson(`${API_BASE}/api/conflict.json`,
 *      isConflictSnapshot);
 *    return useMemo(
 *      () => ({ events: snapshot?.events ?? EMPTY_EVENTS }),
 *      [snapshot],
 *    );
 *
 *  The validator stays the same. The fixture import goes away. The cache
 *  + retry semantics come from useFetchJson, mirroring useGdacsAlerts.
 *  No call-site changes required. */
export function useConflictEvents(): { events: ConflictEvent[] } {
  return useMemo(() => ({ events: VALIDATED?.events ?? EMPTY_EVENTS }), []);
}
